// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaJobMgrTxChannel_Channel_Output_H
#define LpsSaJobMgrTxChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/DemoAppTxChannel/DemoAppTxChannel.h>

DefineOutputChannel(DemoAppTxChannel.Channel.Output, DemoAppTxChannel)

#endif

