// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaJobMgrReqstChannel_Channel_Input_H
#define LpsSaJobMgrReqstChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaJobMgrReqstChannel/LpsSaJobMgrReqstChannel.h>

DefineInputChannel(LpsSaJobMgrReqstChannel.Channel.Input, LpsSaJobMgrReqstChannel)

#endif

