// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'
#include "channel.h"
#include <ais/PluginProcessor/PluginDefine.h>

RegisterPlugin(LpsSaJobMgrTxChannel.Channel.Output, interfaces::Interface, LpsSaJobMgrTxChannelOutputChannel)
