// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaJobMgrTxChannel_Channel_Output_H
#define LpsSaJobMgrTxChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaJobMgrTxChannel/LpsSaJobMgrTxChannel.h>

DefineOutputChannel(LpsSaJobMgrTxChannel.Channel.Output, LpsSaJobMgrTxChannel)

#endif

