// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef DemoAppTxChannel_Channel_Input_H
#define DemoAppTxChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/DemoAppTxChannel/DemoAppTxChannel.h>

DefineInputChannel(DemoAppTxChannel.Channel.Input, DemoAppTxChannel)

#endif

