// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaWeighDebugChannel_Channel_Output_H
#define LpsSaWeighDebugChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaWeighDebugChannel/LpsSaWeighDebugChannel.h>

DefineOutputChannel(LpsSaWeighDebugChannel.Channel.Output, LpsSaWeighDebugChannel)

#endif

