// Do NOT modify -- Auto-generated by ${Filename}

#ifndef ${DataType}_Channel_${InOut}_H
#define ${DataType}_Channel_${InOut}_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <${PathToDataType}>

Define${InOut}Channel(${IntfName}, ${DataType})

#endif

