// Do NOT modify -- Auto-generated by ${Filename}

#include <ais/serialization/TypeRestorer.h>
#include <ais/interfaces/traits/csvable.h>
#include <${PathToDataType}>

extern "C"
{
  csvable* getCSVable(const void* blob, const unsigned int size)
  {
    TypeRestorer rest;
    return rest.restoreAltType<${DataType}, csvable*>(blob, size);
  }
}

