// Do NOT modify -- Auto-generated by ${Filename}

#include <ais/serialization/TypeRestorer.h>
#include <ais/serialization/Restorable.h>
#include <${PathToDataType}>

extern "C"
{
  Restorable* getRestorable(const void* blob, const unsigned int size)
  {
    TypeRestorer rest;
    return rest.restoreAltType<${DataType}, Restorable*>(blob, size);
  }
}

