// Do NOT modify -- Auto-generated by ${Filename}

#include <ais/serialization/TypeRestorer.h>
#include <ais/interfaces/traits/TextWritable.h>
#include <${PathToDataType}>

extern "C"
{
  TextWritable* getTextWritable(const void* blob, const unsigned int size)
  {
    TypeRestorer rest;
    return rest.restoreAltType<${DataType}, TextWritable*>(blob, size);
  }
}

