// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef Machine_Channel_Output_H
#define Machine_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/Machine/Machine.h>

DefineOutputChannel(Machine.Channel.Output, Machine)

#endif

