// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'
#include "../../../WidgetsDebugData/Channel/Output/channel.h"

#include <ais/PluginProcessor/PluginDefine.h>

RegisterPlugin(WidgetsDebugData.Channel.Output, interfaces::Interface, WidgetsDebugDataOutputChannel)
