// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef WidgetsDebugData_Channel_Output_H
#define WidgetsDebugData_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/WidgetsDebugData/WidgetsDebugData.h>

DefineOutputChannel(WidgetsDebugData.Channel.Output, WidgetsDebugData)

#endif

