// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaWeighRespChannel_Channel_Input_H
#define LpsSaWeighRespChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaWeighRespChannel/LpsSaWeighRespChannel.h>

DefineInputChannel(LpsSaWeighRespChannel.Channel.Input, LpsSaWeighRespChannel)

#endif

