require "Acd2Task_TripDataManager_Enums.rb"
require "Acd2Task_DatalinkManager_Enums.rb"

# Add Trip and Cummulatives NVM files
# Each Cumulative must have a pair of keys ending with "_Trips" and "_Cums"
NvmBlockConfig.update({ 
# Trips
   "Trip_A"                =>  { "Size" => 40, "Type" => NvmBlockType::APP,     "Integrity" => NvmBlockIntegrity::RAW, },
   # "Trip_B"                =>  { "Size" => 40, "Type" => NvmBlockType::APP,     "Integrity" => NvmBlockIntegrity::RAW, },

# Cumulatives
   "Load_Count_Trips"     =>  { "Size" => 8,  "Type" => NvmBlockType::APP,     "Integrity" => NvmBlockIntegrity::RAW, },
   "Load_Count_Cums"      =>  { "Size" => 8,  "Type" => NvmBlockType::APP,     "Integrity" => NvmBlockIntegrity::RAW, },
   "Payload_Weight_Trips" =>  { "Size" => 8,  "Type" => NvmBlockType::APP,     "Integrity" => NvmBlockIntegrity::RAW, },
   "Payload_Weight_Cums"  =>  { "Size" => 8,  "Type" => NvmBlockType::APP,     "Integrity" => NvmBlockIntegrity::RAW, },
   "Odometer_Trips"       =>  { "Size" => 8,  "Type" => NvmBlockType::APP,     "Integrity" => NvmBlockIntegrity::RAW, },
   "Odometer_Cums"        =>  { "Size" => 8,  "Type" => NvmBlockType::APP,     "Integrity" => NvmBlockIntegrity::RAW, },
   "Travel_Time_Trips"    =>  { "Size" => 8,  "Type" => NvmBlockType::APP,     "Integrity" => NvmBlockIntegrity::RAW, },
   "Travel_Time_Cums"     =>  { "Size" => 8,  "Type" => NvmBlockType::APP,     "Integrity" => NvmBlockIntegrity::RAW, },
})

module TripID
  A = 0
  B = 1
end

# TaskPlugin configuration
TripDataManager = {
  # Flag for enabling/disabling the plugin
  "enabled" => true,

  # CAN port for trip data
  # Valid values: Datalink::Port::CAN1,2,3,4
  "canPort" => Datalink::Port::CAN1,

  # Version of the cumulative and trip configurations, used in crc calculation
  "version" => 1,

  # The number of seconds between nvm updates. If this 
  # value is below the minimum update time of 1 hour and 
  # the memory type is not BBRAM it will be set to the 
  # minimum value of 1 hour without an error or warning 
  "nvm_update_rate_default" => 5,

  # Trip Configuration, used to populate scl_trips_trip_config_t object
  "Trips" => {
    
    # Name of the Trip, must *exactly* the corresponding key in NvmBlockConfig (will be used as the NVM file name)
    "Trip_A" => {

      # Number of segments used in this trip
      "num_segments" => 1,

      # Maximum number of cumulative entries
      "max_cum_entries" => 5,

      # Maximum number of status entries
      "max_status_entries" => 0,

      # Unique trip identification number to be managed by app
      "trip_id" => TripID::A,

      # Trip type
      "trip_type" => TripType::TRIP,
    },

    # "Trip_B" => {
    #   ...
    # },
  },

  # Cumulative entry configurations, used to populate scl_trips_cum_entry_config_t and scl_cums_cum_config_t objects
  "Cumulatives" => {

    # Name of the Trip, must *exactly* the corresponding keys in NvmBlockConfig minus the "_Trips" and "_Cums" suffixes (will be used as the NVM file name)
    "Load_Count" => {

      # Which trip to register this cumulative to
      "trip_id" => TripID::A,

      # CDL PID for this cumulative
      "param_id" => 0xFC06,

      # Source of the parameter.
      # DATALINK_TX => located in Acd2Task_DatalinkManager_Tx.rb, generated by application for transmission to other ECMs
      # DATALINK_RX => located in Acd2Task_DatalinkManager_Rx.rb, received by application from other ECMs
      # Defaults to DATALINK_TX
      "param_source" => Datalink::ParameterWriteMethod::DATALINK_TX,

      # (Optional) flags for cumulative
      "flg" => CumulativeFlag::NONE,

      # Cumulative type
      "cumulative_type" => CumulativeType::DATA_CUMULATIVE,

      # (Optional) Overrides nvm_update_rate_default
      "nvm_update_rate" => 10,

      # (Optional) Value at which the first rollover occurs if non-zero 
      "rollover1" => 0,

      # (Optional) Value at which the second rollover occurs if non-zero. This must be zero if rollover1 is zero
      "rollover2" => 0,

      # Cums data order
      "data_order" => CumulativeDataOrder::LSB_FIRST,

      # (Optional) Cums data sign. Required if using the default callback functions
      "data_sign" => CumulativeSign::UNSIGNED,
    },

    "Payload_Weight" => {
      "trip_id" => TripID::A,
      "param_id" => 0xFCF8,
      "param_source" => Datalink::ParameterWriteMethod::DATALINK_TX,
      "cumulative_type" => CumulativeType::DATA_CUMULATIVE,
      "data_order" => CumulativeDataOrder::LSB_FIRST,
      "data_sign" => CumulativeSign::UNSIGNED,
    },

    "Odometer" => {
      "trip_id" => TripID::A,
      "param_id" => 0xFC2E,
      "param_source" => Datalink::ParameterWriteMethod::DATALINK_RX,
      "cumulative_type" => CumulativeType::DATA_CUMULATIVE,
      "data_order" => CumulativeDataOrder::LSB_FIRST,
      "data_sign" => CumulativeSign::UNSIGNED,
    },

    "Travel_Time" => {
      "trip_id" => TripID::A,
      "param_id" => 0xFD04,
      "param_source" => Datalink::ParameterWriteMethod::DATALINK_TX,
      "cumulative_type" => CumulativeType::DATA_CUMULATIVE,
      "data_order" => CumulativeDataOrder::LSB_FIRST,
      "data_sign" => CumulativeSign::UNSIGNED,
    },
  },
}
