DatalinkParameterRxConfig.push({
  # Gen7 Middleware Rx subscription example.
  # - GEN7_MIDDLEWARE_ID must match the middleware topic name exactly.
  # - SERVER_NAME must reference an existing server entry (e.g. "Engine", "Chassis").
  # - REQUEST_TYPE should be BROADCAST for callback-driven subscriptions.
  # - REQUEST_RATE_MS is not required for BROADCAST.
  # - PORT, PRIORITY, CAN_ID, START_BIT are not applicable for GEN7_MIDDLEWARE.
  "Machine State Protobuf" => {
    Datalink::Keys::PARAMETER_TYPE       => Datalink::ParameterType::GEN7_MIDDLEWARE,
    Datalink::Keys::GEN7_MIDDLEWARE_ID   => "Engine.machine_state",
    Datalink::Keys::SERVER_NAME          => "Engine",
    Datalink::Keys::PROTOCOL_TYPE        => Datalink::Protocol::GEN7_MIDDLEWARE,
    Datalink::Keys::REQUEST_TYPE         => Datalink::RequestType::BROADCAST,
    Datalink::Keys::REQUEST_RATE_MS      => Datalink::NA,
    Datalink::Keys::DIAG_SUPPORTED       => false,
    Datalink::Keys::QUALIFIED_DATA_TYPE  => Datalink::QualifiedDataType::NA,
  },

  "Product Link Module GPS Position Status" => {
    Datalink::Keys::ID                   => 0xF84D,
    Datalink::Keys::PARAMETER_TYPE       => Datalink::ParameterType::PID,
    Datalink::Keys::SERVER_NAME          => "Telematics",
    Datalink::Keys::PROTOCOL_TYPE        => Datalink::Protocol::J1939,
    Datalink::Keys::REQUEST_TYPE         => Datalink::RequestType::READ_POLL,
    Datalink::Keys::REQUEST_RATE_MS      => 1000,
    Datalink::Keys::PORT                 => Datalink::Port::CAN1,
    Datalink::Keys::PRIORITY             => "NA",
    Datalink::Keys::DIAG_SUPPORTED       => Datalink::Supported::YES,
    Datalink::Keys::RESTRICTED_READ_PID  => "NA",
    Datalink::Keys::CONTROL_BIT_FIELD    => Datalink::ControlBitField::NA,
    Datalink::Keys::SPN_LIST             => "NA",
    Datalink::Keys::QUALIFIED_DATA_TYPE  => Datalink::QualifiedDataType::NA,
    Datalink::Keys::CAN_ID               => "NA",
    Datalink::Keys::START_BIT            => "NA",
  },

  "Actual Engine RPM" => {
    Datalink::Keys::ID                   => 0x40,
    Datalink::Keys::PARAMETER_TYPE       => Datalink::ParameterType::PID,
    Datalink::Keys::SERVER_NAME          => "Engine",
    Datalink::Keys::PROTOCOL_TYPE        => Datalink::Protocol::J1939,
    Datalink::Keys::REQUEST_TYPE         => Datalink::RequestType::PGB,
    Datalink::Keys::REQUEST_RATE_MS      => 500,
    Datalink::Keys::PORT                 => Datalink::Port::CAN1,
    Datalink::Keys::PRIORITY             => "NA",
    Datalink::Keys::DIAG_SUPPORTED       => Datalink::Supported::YES,
    Datalink::Keys::RESTRICTED_READ_PID  => "NA",
    Datalink::Keys::CONTROL_BIT_FIELD    => Datalink::ControlBitField::NA,
    Datalink::Keys::SPN_LIST             => "NA",
    Datalink::Keys::QUALIFIED_DATA_TYPE  => Datalink::QualifiedDataType::NA,
    Datalink::Keys::CAN_ID               => "NA",
    Datalink::Keys::START_BIT            => "NA",
  },

  "Production Measurement Feature Enable Status" => {
    Datalink::Keys::ID                   => 0xD10EE7,
    Datalink::Keys::PARAMETER_TYPE       => Datalink::ParameterType::PID,
    Datalink::Keys::SERVER_NAME          => "Engine",
    Datalink::Keys::PROTOCOL_TYPE        => Datalink::Protocol::J1939,
    Datalink::Keys::REQUEST_TYPE         => Datalink::RequestType::PGB,
    Datalink::Keys::REQUEST_RATE_MS      => 500,
    Datalink::Keys::PORT                 => Datalink::Port::CAN1,
    Datalink::Keys::PRIORITY             => "NA",
    Datalink::Keys::DIAG_SUPPORTED       => Datalink::Supported::YES,
    Datalink::Keys::RESTRICTED_READ_PID  => "NA",
    Datalink::Keys::CONTROL_BIT_FIELD    => Datalink::ControlBitField::NA,
    Datalink::Keys::SPN_LIST             => "NA",
    Datalink::Keys::QUALIFIED_DATA_TYPE  => Datalink::QualifiedDataType::NA,
    Datalink::Keys::CAN_ID               => "NA",
    Datalink::Keys::START_BIT            => "NA",
  },

  "<SEA> Production Measurement Level 2 Feature Installation Status" => {
    Datalink::Keys::ID                   => 0xD11884,
    Datalink::Keys::PARAMETER_TYPE       => Datalink::ParameterType::PID,
    Datalink::Keys::SERVER_NAME          => "Engine",
    Datalink::Keys::PROTOCOL_TYPE        => Datalink::Protocol::J1939,
    Datalink::Keys::REQUEST_TYPE         => Datalink::RequestType::PGB,
    Datalink::Keys::REQUEST_RATE_MS      => 500,
    Datalink::Keys::PORT                 => Datalink::Port::CAN1,
    Datalink::Keys::PRIORITY             => "NA",
    Datalink::Keys::DIAG_SUPPORTED       => Datalink::Supported::YES,
    Datalink::Keys::RESTRICTED_READ_PID  => "NA",
    Datalink::Keys::CONTROL_BIT_FIELD    => Datalink::ControlBitField::NA,
    Datalink::Keys::SPN_LIST             => "NA",
    Datalink::Keys::QUALIFIED_DATA_TYPE  => Datalink::QualifiedDataType::NA,
    Datalink::Keys::CAN_ID               => "NA",
    Datalink::Keys::START_BIT            => "NA",
  },

  "<SEA> Guidance Assisted Steering System Installation Status" => {
    Datalink::Keys::ID                   => 0xD1182A,
    Datalink::Keys::PARAMETER_TYPE       => Datalink::ParameterType::PID,
    Datalink::Keys::SERVER_NAME          => "Engine",
    Datalink::Keys::PROTOCOL_TYPE        => Datalink::Protocol::J1939,
    Datalink::Keys::REQUEST_TYPE         => Datalink::RequestType::PGB,
    Datalink::Keys::REQUEST_RATE_MS      => 500,
    Datalink::Keys::PORT                 => Datalink::Port::CAN1,
    Datalink::Keys::PRIORITY             => "NA",
    Datalink::Keys::DIAG_SUPPORTED       => Datalink::Supported::YES,
    Datalink::Keys::RESTRICTED_READ_PID  => "NA",
    Datalink::Keys::CONTROL_BIT_FIELD    => Datalink::ControlBitField::NA,
    Datalink::Keys::SPN_LIST             => "NA",
    Datalink::Keys::QUALIFIED_DATA_TYPE  => Datalink::QualifiedDataType::NA,
    Datalink::Keys::CAN_ID               => "NA",
    Datalink::Keys::START_BIT            => "NA",
  },

  "<SEA> Co-Pilot System Installation Status" => {
    Datalink::Keys::ID                   => 0xD1182D,
    Datalink::Keys::PARAMETER_TYPE       => Datalink::ParameterType::PID,
    Datalink::Keys::SERVER_NAME          => "Engine",
    Datalink::Keys::PROTOCOL_TYPE        => Datalink::Protocol::J1939,
    Datalink::Keys::REQUEST_TYPE         => Datalink::RequestType::PGB,
    Datalink::Keys::REQUEST_RATE_MS      => 500,
    Datalink::Keys::PORT                 => Datalink::Port::CAN1,
    Datalink::Keys::PRIORITY             => "NA",
    Datalink::Keys::DIAG_SUPPORTED       => Datalink::Supported::YES,
    Datalink::Keys::RESTRICTED_READ_PID  => "NA",
    Datalink::Keys::CONTROL_BIT_FIELD    => Datalink::ControlBitField::NA,
    Datalink::Keys::SPN_LIST             => "NA",
    Datalink::Keys::QUALIFIED_DATA_TYPE  => Datalink::QualifiedDataType::NA,
    Datalink::Keys::CAN_ID               => "NA",
    Datalink::Keys::START_BIT            => "NA",
  },

  "<SEA> Tire Monitoring System Installation Status" => {
    Datalink::Keys::ID                   => 0xD10DBD,
    Datalink::Keys::PARAMETER_TYPE       => Datalink::ParameterType::PID,
    Datalink::Keys::SERVER_NAME          => "Engine",
    Datalink::Keys::PROTOCOL_TYPE        => Datalink::Protocol::J1939,
    Datalink::Keys::REQUEST_TYPE         => Datalink::RequestType::PGB,
    Datalink::Keys::REQUEST_RATE_MS      => 500,
    Datalink::Keys::PORT                 => Datalink::Port::CAN1,
    Datalink::Keys::PRIORITY             => "NA",
    Datalink::Keys::DIAG_SUPPORTED       => Datalink::Supported::YES,
    Datalink::Keys::RESTRICTED_READ_PID  => "NA",
    Datalink::Keys::CONTROL_BIT_FIELD    => Datalink::ControlBitField::NA,
    Datalink::Keys::SPN_LIST             => "NA",
    Datalink::Keys::QUALIFIED_DATA_TYPE  => Datalink::QualifiedDataType::NA,
    Datalink::Keys::CAN_ID               => "NA",
    Datalink::Keys::START_BIT            => "NA",
  },

})

