# Standalone mode
listen=YES
listen_ipv6=NO
max_clients=20
max_per_ip=4
listen_port=2122

# Access rights
anonymous_enable=YES
anon_root=/opt/appdata/CPM/
local_enable=NO
write_enable=YES
anon_upload_enable=NO
anon_mkdir_write_enable=NO
anon_other_write_enable=NO

# Security
anon_world_readable_only=YES
connect_from_port_20=NO
hide_ids=YES
pasv_min_port=50000
pasv_max_port=60000
ftp_username=nobody
secure_chroot_dir=/var/lib/empty
seccomp_sandbox=NO

# Features
xferlog_enable=NO
ls_recurse_enable=NO
ascii_download_enable=NO
ascii_upload_enable=NO
async_abor_enable=NO
ftpd_banner=CPM-NVM FTP Server
background=YES

# Performance
one_process_model=NO
idle_session_timeout=120
data_connection_timeout=300
accept_timeout=60
connect_timeout=60
