// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef TipoffModelTestPoints_Channel_Output_H
#define TipoffModelTestPoints_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/TipoffModelTestPoints/TipoffModelTestPoints.h>

DefineOutputChannel(TipoffModelTestPoints.Channel.Output, TipoffModelTestPoints)

#endif

