// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaJobMgrReqstChannel_Channel_Output_H
#define LpsSaJobMgrReqstChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaJobMgrReqstChannel/LpsSaJobMgrReqstChannel.h>

DefineOutputChannel(LpsSaJobMgrReqstChannel.Channel.Output, LpsSaJobMgrReqstChannel)

#endif

