// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaNvmCalOnTheFlyDataChannel_Channel_Input_H
#define LpsSaNvmCalOnTheFlyDataChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaNvmCalOnTheFlyDataChannel/LpsSaNvmCalOnTheFlyDataChannel.h>

DefineInputChannel(LpsSaNvmCalOnTheFlyDataChannel.Channel.Input, LpsSaNvmCalOnTheFlyDataChannel)

#endif

