// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: CPMTicket.proto
// Protobuf C++ Version: 5.27.0

#include "CPMTicket.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace cat {
namespace cpm {
namespace ticket {

inline constexpr Ticket_Timestamp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        time_{nullptr},
        hour_meter_{nullptr},
        local_time_offset_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Ticket_Timestamp::Ticket_Timestamp(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct Ticket_TimestampDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Ticket_TimestampDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Ticket_TimestampDefaultTypeInternal() {}
  union {
    Ticket_Timestamp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Ticket_TimestampDefaultTypeInternal _Ticket_Timestamp_default_instance_;

inline constexpr Ticket_Measurement::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        time_{nullptr},
        weight_{nullptr},
        accuracy_{static_cast< ::cat::cpm::ticket::Ticket_Measurement_ACCURACY >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Ticket_Measurement::Ticket_Measurement(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct Ticket_MeasurementDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Ticket_MeasurementDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Ticket_MeasurementDefaultTypeInternal() {}
  union {
    Ticket_Measurement _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Ticket_MeasurementDefaultTypeInternal _Ticket_Measurement_default_instance_;

inline constexpr Ticket_Subtotal::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        passes_{},
        truck_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        material_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tag_1_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tag_2_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tag_3_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tag_4_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        start_time_{nullptr},
        end_time_{nullptr},
        truck_id_{nullptr},
        truck_target_weight_{nullptr},
        material_id_{nullptr},
        material_density_{nullptr},
        subtotal_weight_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Ticket_Subtotal::Ticket_Subtotal(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct Ticket_SubtotalDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Ticket_SubtotalDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Ticket_SubtotalDefaultTypeInternal() {}
  union {
    Ticket_Subtotal _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Ticket_SubtotalDefaultTypeInternal _Ticket_Subtotal_default_instance_;

inline constexpr Ticket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        subtotals_{},
        ticket_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        start_time_{nullptr},
        end_time_{nullptr},
        ticket_number_{nullptr},
        total_weight_{nullptr},
        trigger_{static_cast< ::cat::cpm::ticket::Ticket_TRIGGER >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Ticket::Ticket(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct TicketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TicketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TicketDefaultTypeInternal() {}
  union {
    Ticket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TicketDefaultTypeInternal _Ticket_default_instance_;
}  // namespace ticket
}  // namespace cpm
}  // namespace cat
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_CPMTicket_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_CPMTicket_2eproto = nullptr;
const ::uint32_t
    TableStruct_CPMTicket_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Timestamp, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Timestamp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Timestamp, _impl_.time_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Timestamp, _impl_.hour_meter_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Timestamp, _impl_.local_time_offset_),
        0,
        1,
        2,
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Measurement, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Measurement, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Measurement, _impl_.time_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Measurement, _impl_.weight_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Measurement, _impl_.accuracy_),
        0,
        1,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.start_time_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.end_time_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.truck_id_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.truck_name_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.truck_target_weight_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.material_id_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.material_name_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.material_density_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.tag_1_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.tag_2_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.tag_3_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.tag_4_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.subtotal_weight_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket_Subtotal, _impl_.passes_),
        0,
        1,
        2,
        ~0u,
        3,
        4,
        ~0u,
        5,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        6,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket, _impl_.trigger_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket, _impl_.start_time_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket, _impl_.end_time_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket, _impl_.ticket_id_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket, _impl_.ticket_number_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket, _impl_.total_weight_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket, _impl_.subtotals_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::ticket::Ticket, _impl_.text_),
        ~0u,
        0,
        1,
        ~0u,
        2,
        3,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::cat::cpm::ticket::Ticket_Timestamp)},
        {14, 25, -1, sizeof(::cat::cpm::ticket::Ticket_Measurement)},
        {28, 50, -1, sizeof(::cat::cpm::ticket::Ticket_Subtotal)},
        {64, 80, -1, sizeof(::cat::cpm::ticket::Ticket)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::cat::cpm::ticket::_Ticket_Timestamp_default_instance_._instance,
    &::cat::cpm::ticket::_Ticket_Measurement_default_instance_._instance,
    &::cat::cpm::ticket::_Ticket_Subtotal_default_instance_._instance,
    &::cat::cpm::ticket::_Ticket_default_instance_._instance,
};
const char descriptor_table_protodef_CPMTicket_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017CPMTicket.proto\022\016cat.cpm.ticket\032\037googl"
    "e/protobuf/timestamp.proto\032\036google/proto"
    "buf/wrappers.proto\"\312\n\n\006Ticket\022/\n\007trigger"
    "\030\001 \001(\0162\036.cat.cpm.ticket.Ticket.TRIGGER\0224"
    "\n\nstart_time\030\002 \001(\0132 .cat.cpm.ticket.Tick"
    "et.Timestamp\0222\n\010end_time\030\003 \001(\0132 .cat.cpm"
    ".ticket.Ticket.Timestamp\022\021\n\tticket_id\030\004 "
    "\001(\t\0223\n\rticket_number\030\005 \001(\0132\034.google.prot"
    "obuf.UInt32Value\0221\n\014total_weight\030\006 \001(\0132\033"
    ".google.protobuf.FloatValue\0222\n\tsubtotals"
    "\030\007 \003(\0132\037.cat.cpm.ticket.Ticket.Subtotal\022"
    "\014\n\004text\030\010 \001(\t\032\237\001\n\tTimestamp\022(\n\004time\030\001 \001("
    "\0132\032.google.protobuf.Timestamp\0220\n\nhour_me"
    "ter\030\002 \001(\0132\034.google.protobuf.UInt32Value\022"
    "6\n\021local_time_offset\030\003 \001(\0132\033.google.prot"
    "obuf.Int32Value\032\336\001\n\013Measurement\022.\n\004time\030"
    "\001 \001(\0132 .cat.cpm.ticket.Ticket.Timestamp\022"
    "+\n\006weight\030\002 \001(\0132\033.google.protobuf.FloatV"
    "alue\022=\n\010accuracy\030\003 \001(\0162+.cat.cpm.ticket."
    "Ticket.Measurement.ACCURACY\"3\n\010ACCURACY\022"
    "\010\n\004NONE\020\000\022\007\n\003LOW\020\001\022\n\n\006MEDIUM\020\002\022\010\n\004HIGH\020\003"
    "\032\231\004\n\010Subtotal\0224\n\nstart_time\030\001 \001(\0132 .cat."
    "cpm.ticket.Ticket.Timestamp\0222\n\010end_time\030"
    "\002 \001(\0132 .cat.cpm.ticket.Ticket.Timestamp\022"
    ".\n\010truck_id\030\003 \001(\0132\034.google.protobuf.UInt"
    "32Value\022\022\n\ntruck_name\030\004 \001(\t\0228\n\023truck_tar"
    "get_weight\030\005 \001(\0132\033.google.protobuf.Float"
    "Value\0221\n\013material_id\030\006 \001(\0132\034.google.prot"
    "obuf.UInt32Value\022\025\n\rmaterial_name\030\007 \001(\t\022"
    "5\n\020material_density\030\010 \001(\0132\033.google.proto"
    "buf.FloatValue\022\r\n\005tag_1\030\t \001(\t\022\r\n\005tag_2\030\n"
    " \001(\t\022\r\n\005tag_3\030\013 \001(\t\022\r\n\005tag_4\030\014 \001(\t\0224\n\017su"
    "btotal_weight\030\r \001(\0132\033.google.protobuf.Fl"
    "oatValue\0222\n\006passes\030\016 \003(\0132\".cat.cpm.ticke"
    "t.Ticket.Measurement\"I\n\007TRIGGER\022\010\n\004AUTO\020"
    "\000\022\030\n\024TICKET_NOT_FOR_TRADE\020\001\022\032\n\026TICKET_LE"
    "GAL_FOR_TRADE\020\002b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_CPMTicket_2eproto_deps[2] =
    {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
        &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
};
static ::absl::once_flag descriptor_table_CPMTicket_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_CPMTicket_2eproto = {
    false,
    false,
    1463,
    descriptor_table_protodef_CPMTicket_2eproto,
    "CPMTicket.proto",
    &descriptor_table_CPMTicket_2eproto_once,
    descriptor_table_CPMTicket_2eproto_deps,
    2,
    4,
    schemas,
    file_default_instances,
    TableStruct_CPMTicket_2eproto::offsets,
    file_level_enum_descriptors_CPMTicket_2eproto,
    file_level_service_descriptors_CPMTicket_2eproto,
};
namespace cat {
namespace cpm {
namespace ticket {
const ::google::protobuf::EnumDescriptor* Ticket_Measurement_ACCURACY_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_CPMTicket_2eproto);
  return file_level_enum_descriptors_CPMTicket_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Ticket_Measurement_ACCURACY_internal_data_[] = {
    262144u, 0u, };
bool Ticket_Measurement_ACCURACY_IsValid(int value) {
  return 0 <= value && value <= 3;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr Ticket_Measurement_ACCURACY Ticket_Measurement::NONE;
constexpr Ticket_Measurement_ACCURACY Ticket_Measurement::LOW;
constexpr Ticket_Measurement_ACCURACY Ticket_Measurement::MEDIUM;
constexpr Ticket_Measurement_ACCURACY Ticket_Measurement::HIGH;
constexpr Ticket_Measurement_ACCURACY Ticket_Measurement::ACCURACY_MIN;
constexpr Ticket_Measurement_ACCURACY Ticket_Measurement::ACCURACY_MAX;
constexpr int Ticket_Measurement::ACCURACY_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* Ticket_TRIGGER_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_CPMTicket_2eproto);
  return file_level_enum_descriptors_CPMTicket_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t Ticket_TRIGGER_internal_data_[] = {
    196608u, 0u, };
bool Ticket_TRIGGER_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr Ticket_TRIGGER Ticket::AUTO;
constexpr Ticket_TRIGGER Ticket::TICKET_NOT_FOR_TRADE;
constexpr Ticket_TRIGGER Ticket::TICKET_LEGAL_FOR_TRADE;
constexpr Ticket_TRIGGER Ticket::TRIGGER_MIN;
constexpr Ticket_TRIGGER Ticket::TRIGGER_MAX;
constexpr int Ticket::TRIGGER_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class Ticket_Timestamp::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Ticket_Timestamp>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Ticket_Timestamp, _impl_._has_bits_);
};

void Ticket_Timestamp::clear_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.time_ != nullptr) _impl_.time_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void Ticket_Timestamp::clear_hour_meter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.hour_meter_ != nullptr) _impl_.hour_meter_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void Ticket_Timestamp::clear_local_time_offset() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.local_time_offset_ != nullptr) _impl_.local_time_offset_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
Ticket_Timestamp::Ticket_Timestamp(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cat.cpm.ticket.Ticket.Timestamp)
}
inline PROTOBUF_NDEBUG_INLINE Ticket_Timestamp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cat::cpm::ticket::Ticket_Timestamp& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Ticket_Timestamp::Ticket_Timestamp(
    ::google::protobuf::Arena* arena,
    const Ticket_Timestamp& from)
    : ::google::protobuf::Message(arena) {
  Ticket_Timestamp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.time_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(
                              arena, *from._impl_.time_)
                        : nullptr;
  _impl_.hour_meter_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::UInt32Value>(
                              arena, *from._impl_.hour_meter_)
                        : nullptr;
  _impl_.local_time_offset_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Int32Value>(
                              arena, *from._impl_.local_time_offset_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:cat.cpm.ticket.Ticket.Timestamp)
}
inline PROTOBUF_NDEBUG_INLINE Ticket_Timestamp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Ticket_Timestamp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, time_),
           0,
           offsetof(Impl_, local_time_offset_) -
               offsetof(Impl_, time_) +
               sizeof(Impl_::local_time_offset_));
}
Ticket_Timestamp::~Ticket_Timestamp() {
  // @@protoc_insertion_point(destructor:cat.cpm.ticket.Ticket.Timestamp)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Ticket_Timestamp::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.time_;
  delete _impl_.hour_meter_;
  delete _impl_.local_time_offset_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Ticket_Timestamp::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Ticket_Timestamp, _impl_._cached_size_),
              false,
          },
          &Ticket_Timestamp::MergeImpl,
          &Ticket_Timestamp::kDescriptorMethods,
          &descriptor_table_CPMTicket_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 3, 0, 2> Ticket_Timestamp::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Ticket_Timestamp, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Ticket_Timestamp_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cat::cpm::ticket::Ticket_Timestamp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .google.protobuf.Timestamp time = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Ticket_Timestamp, _impl_.time_)}},
    // .google.protobuf.UInt32Value hour_meter = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(Ticket_Timestamp, _impl_.hour_meter_)}},
    // .google.protobuf.Int32Value local_time_offset = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(Ticket_Timestamp, _impl_.local_time_offset_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Timestamp time = 1;
    {PROTOBUF_FIELD_OFFSET(Ticket_Timestamp, _impl_.time_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.UInt32Value hour_meter = 2;
    {PROTOBUF_FIELD_OFFSET(Ticket_Timestamp, _impl_.hour_meter_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Int32Value local_time_offset = 3;
    {PROTOBUF_FIELD_OFFSET(Ticket_Timestamp, _impl_.local_time_offset_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::UInt32Value>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Int32Value>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Ticket_Timestamp::Clear() {
// @@protoc_insertion_point(message_clear_start:cat.cpm.ticket.Ticket.Timestamp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.time_ != nullptr);
      _impl_.time_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.hour_meter_ != nullptr);
      _impl_.hour_meter_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.local_time_offset_ != nullptr);
      _impl_.local_time_offset_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Ticket_Timestamp::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cat.cpm.ticket.Ticket.Timestamp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Timestamp time = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.time_, _impl_.time_->GetCachedSize(), target, stream);
  }

  // .google.protobuf.UInt32Value hour_meter = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.hour_meter_, _impl_.hour_meter_->GetCachedSize(), target, stream);
  }

  // .google.protobuf.Int32Value local_time_offset = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.local_time_offset_, _impl_.local_time_offset_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cat.cpm.ticket.Ticket.Timestamp)
  return target;
}

::size_t Ticket_Timestamp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cat.cpm.ticket.Ticket.Timestamp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // .google.protobuf.Timestamp time = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.time_);
    }

    // .google.protobuf.UInt32Value hour_meter = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.hour_meter_);
    }

    // .google.protobuf.Int32Value local_time_offset = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.local_time_offset_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Ticket_Timestamp::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Ticket_Timestamp*>(&to_msg);
  auto& from = static_cast<const Ticket_Timestamp&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:cat.cpm.ticket.Ticket.Timestamp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.time_ != nullptr);
      if (_this->_impl_.time_ == nullptr) {
        _this->_impl_.time_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(arena, *from._impl_.time_);
      } else {
        _this->_impl_.time_->MergeFrom(*from._impl_.time_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.hour_meter_ != nullptr);
      if (_this->_impl_.hour_meter_ == nullptr) {
        _this->_impl_.hour_meter_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::UInt32Value>(arena, *from._impl_.hour_meter_);
      } else {
        _this->_impl_.hour_meter_->MergeFrom(*from._impl_.hour_meter_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.local_time_offset_ != nullptr);
      if (_this->_impl_.local_time_offset_ == nullptr) {
        _this->_impl_.local_time_offset_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::Int32Value>(arena, *from._impl_.local_time_offset_);
      } else {
        _this->_impl_.local_time_offset_->MergeFrom(*from._impl_.local_time_offset_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Ticket_Timestamp::CopyFrom(const Ticket_Timestamp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cat.cpm.ticket.Ticket.Timestamp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Ticket_Timestamp::InternalSwap(Ticket_Timestamp* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Ticket_Timestamp, _impl_.local_time_offset_)
      + sizeof(Ticket_Timestamp::_impl_.local_time_offset_)
      - PROTOBUF_FIELD_OFFSET(Ticket_Timestamp, _impl_.time_)>(
          reinterpret_cast<char*>(&_impl_.time_),
          reinterpret_cast<char*>(&other->_impl_.time_));
}

::google::protobuf::Metadata Ticket_Timestamp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Ticket_Measurement::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Ticket_Measurement>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Ticket_Measurement, _impl_._has_bits_);
};

void Ticket_Measurement::clear_weight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.weight_ != nullptr) _impl_.weight_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
Ticket_Measurement::Ticket_Measurement(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cat.cpm.ticket.Ticket.Measurement)
}
inline PROTOBUF_NDEBUG_INLINE Ticket_Measurement::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cat::cpm::ticket::Ticket_Measurement& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Ticket_Measurement::Ticket_Measurement(
    ::google::protobuf::Arena* arena,
    const Ticket_Measurement& from)
    : ::google::protobuf::Message(arena) {
  Ticket_Measurement* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.time_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::cat::cpm::ticket::Ticket_Timestamp>(
                              arena, *from._impl_.time_)
                        : nullptr;
  _impl_.weight_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(
                              arena, *from._impl_.weight_)
                        : nullptr;
  _impl_.accuracy_ = from._impl_.accuracy_;

  // @@protoc_insertion_point(copy_constructor:cat.cpm.ticket.Ticket.Measurement)
}
inline PROTOBUF_NDEBUG_INLINE Ticket_Measurement::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Ticket_Measurement::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, time_),
           0,
           offsetof(Impl_, accuracy_) -
               offsetof(Impl_, time_) +
               sizeof(Impl_::accuracy_));
}
Ticket_Measurement::~Ticket_Measurement() {
  // @@protoc_insertion_point(destructor:cat.cpm.ticket.Ticket.Measurement)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Ticket_Measurement::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.time_;
  delete _impl_.weight_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Ticket_Measurement::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Ticket_Measurement, _impl_._cached_size_),
              false,
          },
          &Ticket_Measurement::MergeImpl,
          &Ticket_Measurement::kDescriptorMethods,
          &descriptor_table_CPMTicket_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> Ticket_Measurement::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Ticket_Measurement, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Ticket_Measurement_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cat::cpm::ticket::Ticket_Measurement>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .cat.cpm.ticket.Ticket.Timestamp time = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Ticket_Measurement, _impl_.time_)}},
    // .google.protobuf.FloatValue weight = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(Ticket_Measurement, _impl_.weight_)}},
    // .cat.cpm.ticket.Ticket.Measurement.ACCURACY accuracy = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Ticket_Measurement, _impl_.accuracy_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Ticket_Measurement, _impl_.accuracy_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .cat.cpm.ticket.Ticket.Timestamp time = 1;
    {PROTOBUF_FIELD_OFFSET(Ticket_Measurement, _impl_.time_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.FloatValue weight = 2;
    {PROTOBUF_FIELD_OFFSET(Ticket_Measurement, _impl_.weight_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .cat.cpm.ticket.Ticket.Measurement.ACCURACY accuracy = 3;
    {PROTOBUF_FIELD_OFFSET(Ticket_Measurement, _impl_.accuracy_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }}, {{
    {::_pbi::TcParser::GetTable<::cat::cpm::ticket::Ticket_Timestamp>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::FloatValue>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Ticket_Measurement::Clear() {
// @@protoc_insertion_point(message_clear_start:cat.cpm.ticket.Ticket.Measurement)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.time_ != nullptr);
      _impl_.time_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.weight_ != nullptr);
      _impl_.weight_->Clear();
    }
  }
  _impl_.accuracy_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Ticket_Measurement::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cat.cpm.ticket.Ticket.Measurement)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .cat.cpm.ticket.Ticket.Timestamp time = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.time_, _impl_.time_->GetCachedSize(), target, stream);
  }

  // .google.protobuf.FloatValue weight = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.weight_, _impl_.weight_->GetCachedSize(), target, stream);
  }

  // .cat.cpm.ticket.Ticket.Measurement.ACCURACY accuracy = 3;
  if (this->_internal_accuracy() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this->_internal_accuracy(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cat.cpm.ticket.Ticket.Measurement)
  return target;
}

::size_t Ticket_Measurement::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cat.cpm.ticket.Ticket.Measurement)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .cat.cpm.ticket.Ticket.Timestamp time = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.time_);
    }

    // .google.protobuf.FloatValue weight = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.weight_);
    }

  }
  // .cat.cpm.ticket.Ticket.Measurement.ACCURACY accuracy = 3;
  if (this->_internal_accuracy() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_accuracy());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Ticket_Measurement::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Ticket_Measurement*>(&to_msg);
  auto& from = static_cast<const Ticket_Measurement&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:cat.cpm.ticket.Ticket.Measurement)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.time_ != nullptr);
      if (_this->_impl_.time_ == nullptr) {
        _this->_impl_.time_ =
            ::google::protobuf::Message::CopyConstruct<::cat::cpm::ticket::Ticket_Timestamp>(arena, *from._impl_.time_);
      } else {
        _this->_impl_.time_->MergeFrom(*from._impl_.time_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.weight_ != nullptr);
      if (_this->_impl_.weight_ == nullptr) {
        _this->_impl_.weight_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(arena, *from._impl_.weight_);
      } else {
        _this->_impl_.weight_->MergeFrom(*from._impl_.weight_);
      }
    }
  }
  if (from._internal_accuracy() != 0) {
    _this->_impl_.accuracy_ = from._impl_.accuracy_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Ticket_Measurement::CopyFrom(const Ticket_Measurement& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cat.cpm.ticket.Ticket.Measurement)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Ticket_Measurement::InternalSwap(Ticket_Measurement* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Ticket_Measurement, _impl_.accuracy_)
      + sizeof(Ticket_Measurement::_impl_.accuracy_)
      - PROTOBUF_FIELD_OFFSET(Ticket_Measurement, _impl_.time_)>(
          reinterpret_cast<char*>(&_impl_.time_),
          reinterpret_cast<char*>(&other->_impl_.time_));
}

::google::protobuf::Metadata Ticket_Measurement::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Ticket_Subtotal::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Ticket_Subtotal>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_._has_bits_);
};

void Ticket_Subtotal::clear_truck_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.truck_id_ != nullptr) _impl_.truck_id_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
void Ticket_Subtotal::clear_truck_target_weight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.truck_target_weight_ != nullptr) _impl_.truck_target_weight_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
void Ticket_Subtotal::clear_material_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.material_id_ != nullptr) _impl_.material_id_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
void Ticket_Subtotal::clear_material_density() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.material_density_ != nullptr) _impl_.material_density_->Clear();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
void Ticket_Subtotal::clear_subtotal_weight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.subtotal_weight_ != nullptr) _impl_.subtotal_weight_->Clear();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
Ticket_Subtotal::Ticket_Subtotal(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cat.cpm.ticket.Ticket.Subtotal)
}
inline PROTOBUF_NDEBUG_INLINE Ticket_Subtotal::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cat::cpm::ticket::Ticket_Subtotal& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        passes_{visibility, arena, from.passes_},
        truck_name_(arena, from.truck_name_),
        material_name_(arena, from.material_name_),
        tag_1_(arena, from.tag_1_),
        tag_2_(arena, from.tag_2_),
        tag_3_(arena, from.tag_3_),
        tag_4_(arena, from.tag_4_) {}

Ticket_Subtotal::Ticket_Subtotal(
    ::google::protobuf::Arena* arena,
    const Ticket_Subtotal& from)
    : ::google::protobuf::Message(arena) {
  Ticket_Subtotal* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.start_time_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::cat::cpm::ticket::Ticket_Timestamp>(
                              arena, *from._impl_.start_time_)
                        : nullptr;
  _impl_.end_time_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::cat::cpm::ticket::Ticket_Timestamp>(
                              arena, *from._impl_.end_time_)
                        : nullptr;
  _impl_.truck_id_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::UInt32Value>(
                              arena, *from._impl_.truck_id_)
                        : nullptr;
  _impl_.truck_target_weight_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(
                              arena, *from._impl_.truck_target_weight_)
                        : nullptr;
  _impl_.material_id_ = (cached_has_bits & 0x00000010u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::UInt32Value>(
                              arena, *from._impl_.material_id_)
                        : nullptr;
  _impl_.material_density_ = (cached_has_bits & 0x00000020u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(
                              arena, *from._impl_.material_density_)
                        : nullptr;
  _impl_.subtotal_weight_ = (cached_has_bits & 0x00000040u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(
                              arena, *from._impl_.subtotal_weight_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:cat.cpm.ticket.Ticket.Subtotal)
}
inline PROTOBUF_NDEBUG_INLINE Ticket_Subtotal::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        passes_{visibility, arena},
        truck_name_(arena),
        material_name_(arena),
        tag_1_(arena),
        tag_2_(arena),
        tag_3_(arena),
        tag_4_(arena) {}

inline void Ticket_Subtotal::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, start_time_),
           0,
           offsetof(Impl_, subtotal_weight_) -
               offsetof(Impl_, start_time_) +
               sizeof(Impl_::subtotal_weight_));
}
Ticket_Subtotal::~Ticket_Subtotal() {
  // @@protoc_insertion_point(destructor:cat.cpm.ticket.Ticket.Subtotal)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Ticket_Subtotal::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.truck_name_.Destroy();
  _impl_.material_name_.Destroy();
  _impl_.tag_1_.Destroy();
  _impl_.tag_2_.Destroy();
  _impl_.tag_3_.Destroy();
  _impl_.tag_4_.Destroy();
  delete _impl_.start_time_;
  delete _impl_.end_time_;
  delete _impl_.truck_id_;
  delete _impl_.truck_target_weight_;
  delete _impl_.material_id_;
  delete _impl_.material_density_;
  delete _impl_.subtotal_weight_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Ticket_Subtotal::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_._cached_size_),
              false,
          },
          &Ticket_Subtotal::MergeImpl,
          &Ticket_Subtotal::kDescriptorMethods,
          &descriptor_table_CPMTicket_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 14, 8, 90, 2> Ticket_Subtotal::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_._has_bits_),
    0, // no _extensions_
    14, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294950912,  // skipmap
    offsetof(decltype(_table_), field_entries),
    14,  // num_field_entries
    8,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Ticket_Subtotal_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cat::cpm::ticket::Ticket_Subtotal>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .cat.cpm.ticket.Ticket.Timestamp start_time = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.start_time_)}},
    // .cat.cpm.ticket.Ticket.Timestamp end_time = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.end_time_)}},
    // .google.protobuf.UInt32Value truck_id = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.truck_id_)}},
    // string truck_name = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.truck_name_)}},
    // .google.protobuf.FloatValue truck_target_weight = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 3, 3, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.truck_target_weight_)}},
    // .google.protobuf.UInt32Value material_id = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 4, 4, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.material_id_)}},
    // string material_name = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.material_name_)}},
    // .google.protobuf.FloatValue material_density = 8;
    {::_pbi::TcParser::FastMtS1,
     {66, 5, 5, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.material_density_)}},
    // string tag_1 = 9;
    {::_pbi::TcParser::FastUS1,
     {74, 63, 0, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.tag_1_)}},
    // string tag_2 = 10;
    {::_pbi::TcParser::FastUS1,
     {82, 63, 0, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.tag_2_)}},
    // string tag_3 = 11;
    {::_pbi::TcParser::FastUS1,
     {90, 63, 0, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.tag_3_)}},
    // string tag_4 = 12;
    {::_pbi::TcParser::FastUS1,
     {98, 63, 0, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.tag_4_)}},
    // .google.protobuf.FloatValue subtotal_weight = 13;
    {::_pbi::TcParser::FastMtS1,
     {106, 6, 6, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.subtotal_weight_)}},
    // repeated .cat.cpm.ticket.Ticket.Measurement passes = 14;
    {::_pbi::TcParser::FastMtR1,
     {114, 63, 7, PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.passes_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .cat.cpm.ticket.Ticket.Timestamp start_time = 1;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.start_time_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .cat.cpm.ticket.Ticket.Timestamp end_time = 2;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.end_time_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.UInt32Value truck_id = 3;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.truck_id_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string truck_name = 4;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.truck_name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.FloatValue truck_target_weight = 5;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.truck_target_weight_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.UInt32Value material_id = 6;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.material_id_), _Internal::kHasBitsOffset + 4, 4,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string material_name = 7;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.material_name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.FloatValue material_density = 8;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.material_density_), _Internal::kHasBitsOffset + 5, 5,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string tag_1 = 9;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.tag_1_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string tag_2 = 10;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.tag_2_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string tag_3 = 11;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.tag_3_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string tag_4 = 12;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.tag_4_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.FloatValue subtotal_weight = 13;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.subtotal_weight_), _Internal::kHasBitsOffset + 6, 6,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .cat.cpm.ticket.Ticket.Measurement passes = 14;
    {PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.passes_), -1, 7,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::cat::cpm::ticket::Ticket_Timestamp>()},
    {::_pbi::TcParser::GetTable<::cat::cpm::ticket::Ticket_Timestamp>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::UInt32Value>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::FloatValue>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::UInt32Value>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::FloatValue>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::FloatValue>()},
    {::_pbi::TcParser::GetTable<::cat::cpm::ticket::Ticket_Measurement>()},
  }}, {{
    "\36\0\0\0\12\0\0\15\0\5\5\5\5\0\0\0"
    "cat.cpm.ticket.Ticket.Subtotal"
    "truck_name"
    "material_name"
    "tag_1"
    "tag_2"
    "tag_3"
    "tag_4"
  }},
};

PROTOBUF_NOINLINE void Ticket_Subtotal::Clear() {
// @@protoc_insertion_point(message_clear_start:cat.cpm.ticket.Ticket.Subtotal)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.passes_.Clear();
  _impl_.truck_name_.ClearToEmpty();
  _impl_.material_name_.ClearToEmpty();
  _impl_.tag_1_.ClearToEmpty();
  _impl_.tag_2_.ClearToEmpty();
  _impl_.tag_3_.ClearToEmpty();
  _impl_.tag_4_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.start_time_ != nullptr);
      _impl_.start_time_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.end_time_ != nullptr);
      _impl_.end_time_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.truck_id_ != nullptr);
      _impl_.truck_id_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.truck_target_weight_ != nullptr);
      _impl_.truck_target_weight_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      ABSL_DCHECK(_impl_.material_id_ != nullptr);
      _impl_.material_id_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      ABSL_DCHECK(_impl_.material_density_ != nullptr);
      _impl_.material_density_->Clear();
    }
    if (cached_has_bits & 0x00000040u) {
      ABSL_DCHECK(_impl_.subtotal_weight_ != nullptr);
      _impl_.subtotal_weight_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Ticket_Subtotal::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cat.cpm.ticket.Ticket.Subtotal)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .cat.cpm.ticket.Ticket.Timestamp start_time = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.start_time_, _impl_.start_time_->GetCachedSize(), target, stream);
  }

  // .cat.cpm.ticket.Ticket.Timestamp end_time = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.end_time_, _impl_.end_time_->GetCachedSize(), target, stream);
  }

  // .google.protobuf.UInt32Value truck_id = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.truck_id_, _impl_.truck_id_->GetCachedSize(), target, stream);
  }

  // string truck_name = 4;
  if (!this->_internal_truck_name().empty()) {
    const std::string& _s = this->_internal_truck_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cat.cpm.ticket.Ticket.Subtotal.truck_name");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // .google.protobuf.FloatValue truck_target_weight = 5;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *_impl_.truck_target_weight_, _impl_.truck_target_weight_->GetCachedSize(), target, stream);
  }

  // .google.protobuf.UInt32Value material_id = 6;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, *_impl_.material_id_, _impl_.material_id_->GetCachedSize(), target, stream);
  }

  // string material_name = 7;
  if (!this->_internal_material_name().empty()) {
    const std::string& _s = this->_internal_material_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cat.cpm.ticket.Ticket.Subtotal.material_name");
    target = stream->WriteStringMaybeAliased(7, _s, target);
  }

  // .google.protobuf.FloatValue material_density = 8;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        8, *_impl_.material_density_, _impl_.material_density_->GetCachedSize(), target, stream);
  }

  // string tag_1 = 9;
  if (!this->_internal_tag_1().empty()) {
    const std::string& _s = this->_internal_tag_1();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cat.cpm.ticket.Ticket.Subtotal.tag_1");
    target = stream->WriteStringMaybeAliased(9, _s, target);
  }

  // string tag_2 = 10;
  if (!this->_internal_tag_2().empty()) {
    const std::string& _s = this->_internal_tag_2();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cat.cpm.ticket.Ticket.Subtotal.tag_2");
    target = stream->WriteStringMaybeAliased(10, _s, target);
  }

  // string tag_3 = 11;
  if (!this->_internal_tag_3().empty()) {
    const std::string& _s = this->_internal_tag_3();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cat.cpm.ticket.Ticket.Subtotal.tag_3");
    target = stream->WriteStringMaybeAliased(11, _s, target);
  }

  // string tag_4 = 12;
  if (!this->_internal_tag_4().empty()) {
    const std::string& _s = this->_internal_tag_4();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cat.cpm.ticket.Ticket.Subtotal.tag_4");
    target = stream->WriteStringMaybeAliased(12, _s, target);
  }

  // .google.protobuf.FloatValue subtotal_weight = 13;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        13, *_impl_.subtotal_weight_, _impl_.subtotal_weight_->GetCachedSize(), target, stream);
  }

  // repeated .cat.cpm.ticket.Ticket.Measurement passes = 14;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_passes_size());
       i < n; i++) {
    const auto& repfield = this->_internal_passes().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            14, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cat.cpm.ticket.Ticket.Subtotal)
  return target;
}

::size_t Ticket_Subtotal::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cat.cpm.ticket.Ticket.Subtotal)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .cat.cpm.ticket.Ticket.Measurement passes = 14;
  total_size += 1UL * this->_internal_passes_size();
  for (const auto& msg : this->_internal_passes()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string truck_name = 4;
  if (!this->_internal_truck_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_truck_name());
  }

  // string material_name = 7;
  if (!this->_internal_material_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_material_name());
  }

  // string tag_1 = 9;
  if (!this->_internal_tag_1().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_tag_1());
  }

  // string tag_2 = 10;
  if (!this->_internal_tag_2().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_tag_2());
  }

  // string tag_3 = 11;
  if (!this->_internal_tag_3().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_tag_3());
  }

  // string tag_4 = 12;
  if (!this->_internal_tag_4().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_tag_4());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    // .cat.cpm.ticket.Ticket.Timestamp start_time = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.start_time_);
    }

    // .cat.cpm.ticket.Ticket.Timestamp end_time = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.end_time_);
    }

    // .google.protobuf.UInt32Value truck_id = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.truck_id_);
    }

    // .google.protobuf.FloatValue truck_target_weight = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.truck_target_weight_);
    }

    // .google.protobuf.UInt32Value material_id = 6;
    if (cached_has_bits & 0x00000010u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.material_id_);
    }

    // .google.protobuf.FloatValue material_density = 8;
    if (cached_has_bits & 0x00000020u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.material_density_);
    }

    // .google.protobuf.FloatValue subtotal_weight = 13;
    if (cached_has_bits & 0x00000040u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.subtotal_weight_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Ticket_Subtotal::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Ticket_Subtotal*>(&to_msg);
  auto& from = static_cast<const Ticket_Subtotal&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:cat.cpm.ticket.Ticket.Subtotal)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_passes()->MergeFrom(
      from._internal_passes());
  if (!from._internal_truck_name().empty()) {
    _this->_internal_set_truck_name(from._internal_truck_name());
  }
  if (!from._internal_material_name().empty()) {
    _this->_internal_set_material_name(from._internal_material_name());
  }
  if (!from._internal_tag_1().empty()) {
    _this->_internal_set_tag_1(from._internal_tag_1());
  }
  if (!from._internal_tag_2().empty()) {
    _this->_internal_set_tag_2(from._internal_tag_2());
  }
  if (!from._internal_tag_3().empty()) {
    _this->_internal_set_tag_3(from._internal_tag_3());
  }
  if (!from._internal_tag_4().empty()) {
    _this->_internal_set_tag_4(from._internal_tag_4());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.start_time_ != nullptr);
      if (_this->_impl_.start_time_ == nullptr) {
        _this->_impl_.start_time_ =
            ::google::protobuf::Message::CopyConstruct<::cat::cpm::ticket::Ticket_Timestamp>(arena, *from._impl_.start_time_);
      } else {
        _this->_impl_.start_time_->MergeFrom(*from._impl_.start_time_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.end_time_ != nullptr);
      if (_this->_impl_.end_time_ == nullptr) {
        _this->_impl_.end_time_ =
            ::google::protobuf::Message::CopyConstruct<::cat::cpm::ticket::Ticket_Timestamp>(arena, *from._impl_.end_time_);
      } else {
        _this->_impl_.end_time_->MergeFrom(*from._impl_.end_time_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.truck_id_ != nullptr);
      if (_this->_impl_.truck_id_ == nullptr) {
        _this->_impl_.truck_id_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::UInt32Value>(arena, *from._impl_.truck_id_);
      } else {
        _this->_impl_.truck_id_->MergeFrom(*from._impl_.truck_id_);
      }
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.truck_target_weight_ != nullptr);
      if (_this->_impl_.truck_target_weight_ == nullptr) {
        _this->_impl_.truck_target_weight_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(arena, *from._impl_.truck_target_weight_);
      } else {
        _this->_impl_.truck_target_weight_->MergeFrom(*from._impl_.truck_target_weight_);
      }
    }
    if (cached_has_bits & 0x00000010u) {
      ABSL_DCHECK(from._impl_.material_id_ != nullptr);
      if (_this->_impl_.material_id_ == nullptr) {
        _this->_impl_.material_id_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::UInt32Value>(arena, *from._impl_.material_id_);
      } else {
        _this->_impl_.material_id_->MergeFrom(*from._impl_.material_id_);
      }
    }
    if (cached_has_bits & 0x00000020u) {
      ABSL_DCHECK(from._impl_.material_density_ != nullptr);
      if (_this->_impl_.material_density_ == nullptr) {
        _this->_impl_.material_density_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(arena, *from._impl_.material_density_);
      } else {
        _this->_impl_.material_density_->MergeFrom(*from._impl_.material_density_);
      }
    }
    if (cached_has_bits & 0x00000040u) {
      ABSL_DCHECK(from._impl_.subtotal_weight_ != nullptr);
      if (_this->_impl_.subtotal_weight_ == nullptr) {
        _this->_impl_.subtotal_weight_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(arena, *from._impl_.subtotal_weight_);
      } else {
        _this->_impl_.subtotal_weight_->MergeFrom(*from._impl_.subtotal_weight_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Ticket_Subtotal::CopyFrom(const Ticket_Subtotal& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cat.cpm.ticket.Ticket.Subtotal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Ticket_Subtotal::InternalSwap(Ticket_Subtotal* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.passes_.InternalSwap(&other->_impl_.passes_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.truck_name_, &other->_impl_.truck_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.material_name_, &other->_impl_.material_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tag_1_, &other->_impl_.tag_1_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tag_2_, &other->_impl_.tag_2_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tag_3_, &other->_impl_.tag_3_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tag_4_, &other->_impl_.tag_4_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.subtotal_weight_)
      + sizeof(Ticket_Subtotal::_impl_.subtotal_weight_)
      - PROTOBUF_FIELD_OFFSET(Ticket_Subtotal, _impl_.start_time_)>(
          reinterpret_cast<char*>(&_impl_.start_time_),
          reinterpret_cast<char*>(&other->_impl_.start_time_));
}

::google::protobuf::Metadata Ticket_Subtotal::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Ticket::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Ticket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Ticket, _impl_._has_bits_);
};

void Ticket::clear_ticket_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ticket_number_ != nullptr) _impl_.ticket_number_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
void Ticket::clear_total_weight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.total_weight_ != nullptr) _impl_.total_weight_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
Ticket::Ticket(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cat.cpm.ticket.Ticket)
}
inline PROTOBUF_NDEBUG_INLINE Ticket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cat::cpm::ticket::Ticket& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        subtotals_{visibility, arena, from.subtotals_},
        ticket_id_(arena, from.ticket_id_),
        text_(arena, from.text_) {}

Ticket::Ticket(
    ::google::protobuf::Arena* arena,
    const Ticket& from)
    : ::google::protobuf::Message(arena) {
  Ticket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.start_time_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::cat::cpm::ticket::Ticket_Timestamp>(
                              arena, *from._impl_.start_time_)
                        : nullptr;
  _impl_.end_time_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::cat::cpm::ticket::Ticket_Timestamp>(
                              arena, *from._impl_.end_time_)
                        : nullptr;
  _impl_.ticket_number_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::UInt32Value>(
                              arena, *from._impl_.ticket_number_)
                        : nullptr;
  _impl_.total_weight_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(
                              arena, *from._impl_.total_weight_)
                        : nullptr;
  _impl_.trigger_ = from._impl_.trigger_;

  // @@protoc_insertion_point(copy_constructor:cat.cpm.ticket.Ticket)
}
inline PROTOBUF_NDEBUG_INLINE Ticket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        subtotals_{visibility, arena},
        ticket_id_(arena),
        text_(arena) {}

inline void Ticket::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, start_time_),
           0,
           offsetof(Impl_, trigger_) -
               offsetof(Impl_, start_time_) +
               sizeof(Impl_::trigger_));
}
Ticket::~Ticket() {
  // @@protoc_insertion_point(destructor:cat.cpm.ticket.Ticket)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Ticket::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.ticket_id_.Destroy();
  _impl_.text_.Destroy();
  delete _impl_.start_time_;
  delete _impl_.end_time_;
  delete _impl_.ticket_number_;
  delete _impl_.total_weight_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Ticket::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Ticket, _impl_._cached_size_),
              false,
          },
          &Ticket::MergeImpl,
          &Ticket::kDescriptorMethods,
          &descriptor_table_CPMTicket_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 5, 51, 2> Ticket::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Ticket, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Ticket_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cat::cpm::ticket::Ticket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string text = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(Ticket, _impl_.text_)}},
    // .cat.cpm.ticket.Ticket.TRIGGER trigger = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Ticket, _impl_.trigger_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Ticket, _impl_.trigger_)}},
    // .cat.cpm.ticket.Ticket.Timestamp start_time = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(Ticket, _impl_.start_time_)}},
    // .cat.cpm.ticket.Ticket.Timestamp end_time = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(Ticket, _impl_.end_time_)}},
    // string ticket_id = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Ticket, _impl_.ticket_id_)}},
    // .google.protobuf.UInt32Value ticket_number = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 2, 2, PROTOBUF_FIELD_OFFSET(Ticket, _impl_.ticket_number_)}},
    // .google.protobuf.FloatValue total_weight = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 3, 3, PROTOBUF_FIELD_OFFSET(Ticket, _impl_.total_weight_)}},
    // repeated .cat.cpm.ticket.Ticket.Subtotal subtotals = 7;
    {::_pbi::TcParser::FastMtR1,
     {58, 63, 4, PROTOBUF_FIELD_OFFSET(Ticket, _impl_.subtotals_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .cat.cpm.ticket.Ticket.TRIGGER trigger = 1;
    {PROTOBUF_FIELD_OFFSET(Ticket, _impl_.trigger_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .cat.cpm.ticket.Ticket.Timestamp start_time = 2;
    {PROTOBUF_FIELD_OFFSET(Ticket, _impl_.start_time_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .cat.cpm.ticket.Ticket.Timestamp end_time = 3;
    {PROTOBUF_FIELD_OFFSET(Ticket, _impl_.end_time_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string ticket_id = 4;
    {PROTOBUF_FIELD_OFFSET(Ticket, _impl_.ticket_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.UInt32Value ticket_number = 5;
    {PROTOBUF_FIELD_OFFSET(Ticket, _impl_.ticket_number_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.FloatValue total_weight = 6;
    {PROTOBUF_FIELD_OFFSET(Ticket, _impl_.total_weight_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .cat.cpm.ticket.Ticket.Subtotal subtotals = 7;
    {PROTOBUF_FIELD_OFFSET(Ticket, _impl_.subtotals_), -1, 4,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // string text = 8;
    {PROTOBUF_FIELD_OFFSET(Ticket, _impl_.text_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::cat::cpm::ticket::Ticket_Timestamp>()},
    {::_pbi::TcParser::GetTable<::cat::cpm::ticket::Ticket_Timestamp>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::UInt32Value>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::FloatValue>()},
    {::_pbi::TcParser::GetTable<::cat::cpm::ticket::Ticket_Subtotal>()},
  }}, {{
    "\25\0\0\0\11\0\0\0\4\0\0\0\0\0\0\0"
    "cat.cpm.ticket.Ticket"
    "ticket_id"
    "text"
  }},
};

PROTOBUF_NOINLINE void Ticket::Clear() {
// @@protoc_insertion_point(message_clear_start:cat.cpm.ticket.Ticket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.subtotals_.Clear();
  _impl_.ticket_id_.ClearToEmpty();
  _impl_.text_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.start_time_ != nullptr);
      _impl_.start_time_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.end_time_ != nullptr);
      _impl_.end_time_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.ticket_number_ != nullptr);
      _impl_.ticket_number_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.total_weight_ != nullptr);
      _impl_.total_weight_->Clear();
    }
  }
  _impl_.trigger_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Ticket::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cat.cpm.ticket.Ticket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .cat.cpm.ticket.Ticket.TRIGGER trigger = 1;
  if (this->_internal_trigger() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_trigger(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .cat.cpm.ticket.Ticket.Timestamp start_time = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.start_time_, _impl_.start_time_->GetCachedSize(), target, stream);
  }

  // .cat.cpm.ticket.Ticket.Timestamp end_time = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.end_time_, _impl_.end_time_->GetCachedSize(), target, stream);
  }

  // string ticket_id = 4;
  if (!this->_internal_ticket_id().empty()) {
    const std::string& _s = this->_internal_ticket_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cat.cpm.ticket.Ticket.ticket_id");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // .google.protobuf.UInt32Value ticket_number = 5;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *_impl_.ticket_number_, _impl_.ticket_number_->GetCachedSize(), target, stream);
  }

  // .google.protobuf.FloatValue total_weight = 6;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, *_impl_.total_weight_, _impl_.total_weight_->GetCachedSize(), target, stream);
  }

  // repeated .cat.cpm.ticket.Ticket.Subtotal subtotals = 7;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_subtotals_size());
       i < n; i++) {
    const auto& repfield = this->_internal_subtotals().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            7, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // string text = 8;
  if (!this->_internal_text().empty()) {
    const std::string& _s = this->_internal_text();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cat.cpm.ticket.Ticket.text");
    target = stream->WriteStringMaybeAliased(8, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cat.cpm.ticket.Ticket)
  return target;
}

::size_t Ticket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cat.cpm.ticket.Ticket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .cat.cpm.ticket.Ticket.Subtotal subtotals = 7;
  total_size += 1UL * this->_internal_subtotals_size();
  for (const auto& msg : this->_internal_subtotals()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string ticket_id = 4;
  if (!this->_internal_ticket_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_ticket_id());
  }

  // string text = 8;
  if (!this->_internal_text().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_text());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // .cat.cpm.ticket.Ticket.Timestamp start_time = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.start_time_);
    }

    // .cat.cpm.ticket.Ticket.Timestamp end_time = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.end_time_);
    }

    // .google.protobuf.UInt32Value ticket_number = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.ticket_number_);
    }

    // .google.protobuf.FloatValue total_weight = 6;
    if (cached_has_bits & 0x00000008u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.total_weight_);
    }

  }
  // .cat.cpm.ticket.Ticket.TRIGGER trigger = 1;
  if (this->_internal_trigger() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_trigger());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Ticket::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Ticket*>(&to_msg);
  auto& from = static_cast<const Ticket&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:cat.cpm.ticket.Ticket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_subtotals()->MergeFrom(
      from._internal_subtotals());
  if (!from._internal_ticket_id().empty()) {
    _this->_internal_set_ticket_id(from._internal_ticket_id());
  }
  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.start_time_ != nullptr);
      if (_this->_impl_.start_time_ == nullptr) {
        _this->_impl_.start_time_ =
            ::google::protobuf::Message::CopyConstruct<::cat::cpm::ticket::Ticket_Timestamp>(arena, *from._impl_.start_time_);
      } else {
        _this->_impl_.start_time_->MergeFrom(*from._impl_.start_time_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.end_time_ != nullptr);
      if (_this->_impl_.end_time_ == nullptr) {
        _this->_impl_.end_time_ =
            ::google::protobuf::Message::CopyConstruct<::cat::cpm::ticket::Ticket_Timestamp>(arena, *from._impl_.end_time_);
      } else {
        _this->_impl_.end_time_->MergeFrom(*from._impl_.end_time_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.ticket_number_ != nullptr);
      if (_this->_impl_.ticket_number_ == nullptr) {
        _this->_impl_.ticket_number_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::UInt32Value>(arena, *from._impl_.ticket_number_);
      } else {
        _this->_impl_.ticket_number_->MergeFrom(*from._impl_.ticket_number_);
      }
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.total_weight_ != nullptr);
      if (_this->_impl_.total_weight_ == nullptr) {
        _this->_impl_.total_weight_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(arena, *from._impl_.total_weight_);
      } else {
        _this->_impl_.total_weight_->MergeFrom(*from._impl_.total_weight_);
      }
    }
  }
  if (from._internal_trigger() != 0) {
    _this->_impl_.trigger_ = from._impl_.trigger_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Ticket::CopyFrom(const Ticket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cat.cpm.ticket.Ticket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Ticket::InternalSwap(Ticket* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.subtotals_.InternalSwap(&other->_impl_.subtotals_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ticket_id_, &other->_impl_.ticket_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.text_, &other->_impl_.text_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Ticket, _impl_.trigger_)
      + sizeof(Ticket::_impl_.trigger_)
      - PROTOBUF_FIELD_OFFSET(Ticket, _impl_.start_time_)>(
          reinterpret_cast<char*>(&_impl_.start_time_),
          reinterpret_cast<char*>(&other->_impl_.start_time_));
}

::google::protobuf::Metadata Ticket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ticket
}  // namespace cpm
}  // namespace cat
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_CPMTicket_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
