// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#include <ais/serialization/TypeRestorer.h>
#include <ais/serialization/Restorable.h>
#include <interfaces/LpsSaWeighTxChannel/LpsSaWeighTxChannel.h>

extern "C"  
{
    Restorable *getRestorable(const void *blob, const unsigned int size) 
    {
        TypeRestorer rest;
        return rest.restoreAltType<LpsSaWeighTxChannel, Restorable *>(blob, size); 
    }
}

