// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'
#include "channel.h"
#include <ais/PluginProcessor/PluginDefine.h>

RegisterPlugin(LpsSaWeighReqstChannel.Channel.Input, interfaces::Interface, LpsSaWeighReqstChannelInputChannel)
