// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaWeighReqstChannel_Channel_Input_H
#define LpsSaWeighReqstChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaWeighReqstChannel/LpsSaWeighReqstChannel.h>

DefineInputChannel(LpsSaWeighReqstChannel.Channel.Input, LpsSaWeighReqstChannel)

#endif

