#!/usr/bin/perl
# See README for more context.
#
# inputs:
#   -h shows usage
#   path to data type header file
#   data type class name
#   interface name
#
# checks:
#   run script from anywhere, but insist that CAT_DIR be defined
#     and that $CAT_DIR/prod/common/interfaces exists
#   look for prod/common/interfaces/$clInterfaceName, or bail
#   look for prod/common/interfaces/autogen, or bail
#   look for $clPathToDataType, or bail
#   bail if  prod/common/interfaces/$clInterfaceName/Channel exists
# if preconditions satisfied...
# create directory structure
# generate SConcript, channel.{cc,h} files for input and output variants
# done.

use Getopt::Long;
use strict;
use File::Path;
use Cwd qw(cwd abs_path);

########################################
## Get the current date in order to get the year.
########################################
my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
$year += 1900;  # note $year contains the number of years since 1900, so add on 1900 to get the current year


########################################
## Get command line options
########################################
my $opts = GetOptions(
  'interfaceName|i=s'  => \my $clInterfaceName,
  'pathToDataType|p=s' => \my $clPathToDataType,
  'dataTypeName|d=s'   => \my $clDataType,
  'help|h'             => \my $clHelp,
  'csvable'            => \my $clCsvable,
  'textWritable'     => \my $clTextWritable,
  'restorable|r'       => \my $clRestorable,
  'sconscript|s'       => \my $clOnlyGenerateSConscript,
  'all|a'              => \my $clGenerateAll,
  'fix|f'              => \my $clFix
);

########################################
## Define Constants
########################################
my $currentdir = cwd;
my $onelevelup = abs_path($currentdir . '/..');

#my $catDir                  = $ENV{'CAT_DIR'};
my $interfacesDir           = $currentdir . '/../../interfaces';
my $interfaceDir            = $onelevelup . "/" . $clInterfaceName;
my $channelInputDir         = "$interfaceDir/Channel/Input";
my $channelOutputDir        = "$interfaceDir/Channel/Output";
my $restorableDir           = "$interfaceDir/Restorable";
my $typeTraitsDir           = "$interfaceDir/TypeTraits";
my $channelDir              = "$interfaceDir/Channel";
my $interfacesSConscript    = $onelevelup . '/SConscript';
my $csvableSourceFile       = $typeTraitsDir . "/csvable.cpp";
my $textWritableSourceFile  = $typeTraitsDir . "/textWritable.cpp";
########################################
## Check pre-conditions
########################################
if ( defined $clHelp )
{
  help();
  exit(0);
}



#die "Error: CAT_DIR environment variable not set"  unless ( -d $catDir );
die "Error: $interfacesDir does not exist"         unless ( -d $interfacesDir );
die "Error: $interfacesDir/autogen does not exist" unless ( -d "$interfacesDir/autogen" );

if ( not defined $clDataType )
{
  $clDataType = $clInterfaceName;
}

if ( defined $clFix )
{
  detectComponentsAndGenerateSConscript();
  exit(0);
}

#----------------
# Remove SConscript and obj dir from the input directory";
#----------------
sub removeSConscriptAndObjDir 
{
  my ($thepath) = @_;
  
  # Channel/SConscript
  system ("git-rm", "$thepath/SConscript"); 
  if ( $? == -1 )
  {
    print "command to remove man SConscript failed: $!\n";
  }
  else
  {
    printf "command exited with value %d \n", $? >> 8;
  }
  # Channel/obj
  rmtree "$thepath/obj"; 

}

sub detectComponentsAndGenerateSConscript
{
  print "Detecting configuration of $clInterfaceName (DataType: $clDataType)\n";
  my $somethingThere = 0;

  if ( not -d $interfaceDir )
  {
    printf("$clInterfaceName is not a directory, please specify an interface directory generated by this script.\n");
    exit(1);
  }
  else
  {

    # Check for Channel dir
    if ( -d $channelDir )
    {
      printf("Using Channels...\n");
      $somethingThere = 1;
    }

    # Check for TypeTraits/csvable.cpp
    if ( -f $csvableSourceFile )
    {
      printf("Using Csvable TypeTrait...\n");
      $clCsvable      = 1;
      $somethingThere = 1;
    }

    # Check for TypeTraits/textWritable.cpp
    if ( -f $textWritableSourceFile )
    {
      printf("Using TextWritable TypeTrait...\n");
      $clTextWritable = 1;
      $somethingThere = 1;
    }

    if ( -d $restorableDir )
    {
      printf("Using Restorable...\n");
      $clRestorable   = 1;
      $somethingThere = 1;
    }

    if ($somethingThere)
    {
      makeSConscript($interfaceDir);

############################
# --- Code that can clean up the previous SConscript files in the subdirectories.
############################
#     #
#     # Ok, clean up the old files that were there
#     #
#
#     if ( -f "$channelDir/SConscript" )
#     {
#       &removeSConscriptAndObjDir($channelDir)
#
#       # Channel/Input/SConscript
#       &removeSConscriptAndObjDir($channelInputDir)
#
#       # Channel/Output/SConscript
#       &removeSConscriptAndObjDir($channelOutputDir)
#     }
#
#     # Check for TypeTraits/csvable.cpp
#     if ( "$typeTraitsDir/SConscript" )
#     {
#       &removeSConscriptAndObjDir($typeTraitsDir)
#     }
#
#     # Check for Restorable
#     if ("$restorableDir/SConscript" )
#     {
#       &removeSConscriptAndObjDir($restorableDir)
#     }


      exit(0);
    }
    else
    {
      printf("$interfaceDir does not appear to be an interface directory, aborting...\n");
      exit(1);
    }
  }

  exit(0);
}

if ( not defined $clInterfaceName )
{
  help();
  exit(1);
}

if ( not defined $clPathToDataType )
{
  our $clPathToDataType_our = "interfaces/$clInterfaceName/$clInterfaceName.h";
}

my $clPathToDataType = our $clPathToDataType_our;

print "Path To Data: " . $clPathToDataType . "\n";

########################################
## Make the interfaces
########################################
# Create interface directory if it does not already exist
if ( not -d $interfaceDir )
{
  print("Creating directory $interfaceDir\n");
  system("mkdir -p $interfaceDir");
}

## Define Task State
my $shouldGenerateChannels  = 0;

my $shouldGenerateCsvable       = 0;
my $shouldGenerateTextWritable  = 0;

my $shouldGenerateRestorable      = 0;
my $shouldGenerateSConscript      = 0;
my $shouldGenerateInterfaceTypes  = 0;
my $shouldGenerateInterfaceHeader = 0;

# Channels
if ( not -d $channelDir )
{
  unless ( defined $clOnlyGenerateSConscript ) { printf("Creating Channels...\n"); }
  $shouldGenerateChannels   = 1;
  $shouldGenerateSConscript = 1;
}
else
{
  unless ( defined $clOnlyGenerateSConscript ) { printf("NOT creating Channels (already exists)\n"); }
}

# TypeTraits
#if ( ( not -d $typeTraitsDir ) && ( defined $clCsvable || defined $clTextWritable || defined $clGenerateAll ) )
#{
#  unless ( defined $clOnlyGenerateSConscript ) { printf("Creating TypeTraits...\n"); }
#  $shouldGenerateTypeTraits = 1;
#  $shouldGenerateSConscript = 1;
#}
#elsif ( defined $clCsvable || defined $clTextWritable || defined $clGenerateAll )
#{
#  unless ( defined $clOnlyGenerateSConscript ) { printf("NOT creating TypeTraits (already exists)\n"); }
#}
#

# Csvable Type Trait
if ( defined $clCsvable || defined $clGenerateAll )
{
  unless ( defined $clOnlyGenerateSConscript ) { printf("Creating Csvable TypeTrait...\n"); }

  if ( not -f $csvableSourceFile )
  {
    $shouldGenerateCsvable    = 1;
    $shouldGenerateSConscript = 1;
  }
  else
  {
    print "Csvable Type Trait already exists for this interface.  Not generating.\n";
  }
}

# TextWritable Type Trait
if ( defined $clTextWritable || defined $clGenerateAll )
{
  unless ( defined $clOnlyGenerateSConscript ) { printf("Creating TextWritable TypeTrait...\n"); }

  if ( not -f $textWritableSourceFile )
  {
    $shouldGenerateTextWritable = 1;
    $shouldGenerateSConscript   = 1;
  }
  else
  {
    print "TextWritable Type Trait already exists for this interface.  Not generating.\n";
  }
}

# Restorable
if ( ( not -d $restorableDir ) && ( defined $clRestorable || defined $clGenerateAll ) )
{
  unless ( defined $clOnlyGenerateSConscript ) { printf("Creating Restorable...\n"); }
  $shouldGenerateRestorable = 1;
  $shouldGenerateSConscript = 1;
}
elsif ( defined $clRestorable || defined $clGenerateAll )
{
  unless ( defined $clOnlyGenerateSConscript ) { printf("NOT creating Restorable (already exists)\n"); }
}

# Interface Header
if ( not -f "$interfaceDir/$clInterfaceName.h" )
{
  $shouldGenerateInterfaceHeader = 1;
}

# InterfaceTypes.h
if ( not -f "$interfaceDir/InterfaceTypes.h" )
{
  $shouldGenerateInterfaceTypes = 1;
}

# Do the work
if ( not defined $clOnlyGenerateSConscript )
{
  if ($shouldGenerateChannels)
  {
    makeChannel( "Input",  $channelInputDir );
    makeChannel( "Output", $channelOutputDir );
  }

  if ($shouldGenerateRestorable)
  {
    makeRestorable($restorableDir);
  }

  if ($shouldGenerateCsvable)
  {
    makeCsvable($typeTraitsDir);
  }

  if ($shouldGenerateTextWritable)
  {
    makeTextWritable($typeTraitsDir);
  }

  if ($shouldGenerateInterfaceTypes)
  {
    makeInterfaceTypes();
  }

  if ($shouldGenerateInterfaceHeader)
  {
    makeInterfaceHeader($interfaceDir);
  }

  updateInterfacesSConscript();
}
else    ## Only generate SConscript
{
  $shouldGenerateSConscript = 1;
}

#if ($shouldGenerateSConscript)
#{
  printf("Creating SConscript...\n");
  detectComponentsAndGenerateSConscript();
  #makeSConscript($interfaceDir);
#}

# End Main Execution

########################################
## Define sub-routines
########################################
sub help
{
  print("Usage: \n"
      . "  --help|-h            print this help message\n" . "\n"
      . "  --interfaceName|-i   (required) top-level name of the interface, \n"
      . "                       this will also be the directory name directly under prod/common/interfaces\n"
      . "  --pathToDataType|-p  (optional) path to the data type as it should appear in an #include directive\n"
      . "                       (if omitted, the path is inferred from the -i option)\n"
      . "  --dataTypeName|-d    (optional) class name of the data type\n"
      . "                       (if omitted, the data type is inferred from the -i option)\n"
      . "  --csvable            (optional) generate csvable type trait (can be used on an existing interface)\n"
      . "  --textWritable       (optional) generate textWritable type trait (can be used on an existing interface)\n"
      . "  --restorable|-r      (optional) generate restorable (can be used on an existing interface)\n"
      . "  --all|-a             Same as -t -k -r -w\n"
      . "  --sconsscript|-s     only generate the scons script (will not overwrite other files)\n"
      . "  --fix|-f <name>      Attempts to construct a SConscript from the directory structure <name> = interface name\n"
      . "\nExamples: "
      . "\nTo generate the simplest interface with only Channels:\n"
      . "\t./generate.pl -i SomeNewInterface\n"
      . "\nTo generate an interface that uses everything (Channels, Restorable, TypeTraits):\n"
      . "\t./generate.pl -i SomeNewInterface -a\n"
      . "\nTo generate a SConscript for an existing interface, manually specifying a configuration (i.e. Channels, Restorable, TypeTraits):\n"
      . "\t./generate.pl -i SomeNewInterface -s -r \n"
      . "\nTo generate a SConscript for an existing interface, autodetecting the correct configuration:\n"
      . "\t./generate.pl -f <interface name>\n"
      . "\n" );
}

#####################################################
## makeChannel ("Input" or "Output", TargetDir)
######################################################
sub makeChannel
{
  my $io          = shift;
  my $target_dir  = shift;
  my @sourceFiles = qw( channel.cpp channel.h);

  system("/bin/mkdir -p $target_dir");

  foreach my $filename (@sourceFiles)
  {
    system( "/usr/bin/awk "
        . "-v DataType=\"$clDataType\" "
        . "-v InOut=\"$io\" "
        . "-v PathToDataType=\"$clPathToDataType\" "
        . "-v IntfName=\"$clInterfaceName\" "
        . "-v Year=\"$year\" "
        . "-f $interfacesDir/autogen/genInterface.awk $interfacesDir/autogen/templates/$filename > $target_dir/$filename\n"
    );
  }
}

#####################################################
## makeRestorable (TargetDir)
#####################################################
sub makeRestorable
{
  my $target_dir  = shift;
  my @sourceFiles = qw( Restorable.cpp);

  system("/bin/mkdir -p $target_dir");

  foreach my $filename (@sourceFiles)
  {
    system( "/usr/bin/awk "
        . "-v DataType=\"$clDataType\" "
        . "-v PathToDataType=\"$clPathToDataType\" "
        . "-v Year=\"$year\" "
        . "-f $interfacesDir/autogen/genInterface.awk $interfacesDir/autogen/templates/$filename > $target_dir/$filename\n"
    );
  }
}

#####################################################
## makeRestorable (TargetDir)
#####################################################
sub makeSConscript
{
  my $target_dir       = shift;
  my @sourceFiles      = qw(SConscript);
  my $useCsvable       = "";
  my $useTextWritable  = "";
  my $useRestorable    = "";
  my $useTypeTraits    = "#";

  # Csvable
  if ( ( not defined $clCsvable ) && ( not defined $clGenerateAll ) )
  {
    $useCsvable = "#";
  }

  # TextWritable
  if ( ( not defined $clTextWritable ) && ( not defined $clGenerateAll ) )
  {
    $useTextWritable = "#";
  }

  # Restorable
  if ( ( not defined $clRestorable ) && ( not defined $clGenerateAll ) )
  {
    $useRestorable = "#";
  }

  # TypeTraits
  if ( defined $clCsvable || defined $clTextWritable || defined $clGenerateAll )
  {
    $useTypeTraits = "";
  }

  foreach my $filename (@sourceFiles)
  {
    system( "/usr/bin/awk "
        . "-v DataType=\"$clDataType\" "
        . "-v UseCsvable=\"$useCsvable\" "
        . "-v UseTextWritable=\"$useTextWritable\" "
        . "-v UseRestorable=\"$useRestorable\" "
        . "-v UseTypeTraits=\"$useTypeTraits\" "
        . "-v Year=\"$year\" "
        . "-f $interfacesDir/autogen/genInterface.awk $interfacesDir/autogen/templates/$filename > $target_dir/$filename\n"
    );
  }
}

#####################################################
## makeRestorable (TargetDir, InterfaceName)
#####################################################
sub makeInterfaceHeader
{
  my $target_dir  = shift;
  my @sourceFiles = qw( ifaceHeader.h );

  foreach my $filename (@sourceFiles)
  {
    system( "/usr/bin/awk "
        . "-v DataType=\"$clDataType\" "
        . "-v Year=\"$year\" "
        . "-f $interfacesDir/autogen/genInterface.awk $interfacesDir/autogen/templates/$filename > $target_dir/$clInterfaceName.h\n"
    );
  }
}

#####################################################
## makeCvsable (TargetDir)
#####################################################
sub makeCsvable
{
  my $target_dir  = shift;
  my @sourceFiles = qw( csvable.cpp);

  system("/bin/mkdir -p $target_dir");

  foreach my $filename (@sourceFiles)
  {
    system( "/usr/bin/awk "
        . "-v DataType=\"$clDataType\" "
        . "-v PathToDataType=\"$clPathToDataType\" "
        . "-v Year=\"$year\" "
        . "-f $interfacesDir/autogen/genInterface.awk $interfacesDir/autogen/templates/$filename > $target_dir/$filename\n"
    );
  }
}


#####################################################
## makeTextWritable (TargetDir)
#####################################################
sub makeTextWritable
{
  my $target_dir  = shift;
  my @sourceFiles = qw( textWritable.cpp);

  system("/bin/mkdir -p $target_dir");

  foreach my $filename (@sourceFiles)
  {
    system( "/usr/bin/awk "
        . "-v DataType=\"$clDataType\" "
        . "-v PathToDataType=\"$clPathToDataType\" "
        . "-v Year=\"$year\" "
        . "-f $interfacesDir/autogen/genInterface.awk $interfacesDir/autogen/templates/$filename > $target_dir/$filename\n"
    );
  }
}


#####################################################
## makeInterfaceTypes (none)
#####################################################
sub makeInterfaceTypes
{
  printf("Generating InterfaceTypes.h\n");
  open( INTERFACEFILE, ">>$interfaceDir/InterfaceTypes.h" );
  print INTERFACEFILE "#ifndef _" . $clDataType . "InterfaceTypes_h_\n";
  print INTERFACEFILE "#define _" . $clDataType . "InterfaceTypes_h_\n\n";
  print INTERFACEFILE "#include <ais/interfaces/baseTypes/InputInterface.h>\n";
  print INTERFACEFILE "#include <ais/interfaces/baseTypes/OutputInterface.h>\n";
  print INTERFACEFILE "#include \"" . $clDataType . ".h\"\n\n";
  print INTERFACEFILE "typedef interfaces::baseTypes::InputInterface<" . $clDataType . "> " . $clDataType . "Input;\n";

  print INTERFACEFILE "typedef interfaces::baseTypes::OutputInterface<"
    . $clDataType . "> "
    . $clDataType
    . "Output;\n";
    

  print INTERFACEFILE "\n";
  print INTERFACEFILE "namespace interfaces\n";
  print INTERFACEFILE "{\n";
  print INTERFACEFILE "  template<>\n";
  print INTERFACEFILE "  inline std::string getDefaultInterfaceName<". $clDataType . "Input>()\n";
  print INTERFACEFILE "  {\n";
  print INTERFACEFILE "    return \"". $clDataType . "Input\";\n";
  print INTERFACEFILE "  }\n";
  print INTERFACEFILE "\n";
  print INTERFACEFILE "  template<>\n";
  print INTERFACEFILE "  inline std::string getDefaultInterfaceName<". $clDataType . "Output>()\n";
  print INTERFACEFILE "  {\n";
  print INTERFACEFILE "    return \"". $clDataType . "Output\";\n";
  print INTERFACEFILE "  }\n";
  print INTERFACEFILE "}\n";
  print INTERFACEFILE "\n";

  print INTERFACEFILE "#endif\n";
  close INTERFACEFILE;
}

#####################################################
## Add interface to $interfaceDir/SConscript
#####################################################
sub updateInterfacesSConscript
{
  open my $fh, $interfacesSConscript or die "Could not open $interfacesSConscript: $!";
  my @lines = grep /$clInterfaceName/, <$fh>;
  close $fh;

  if ( scalar(@lines) == 0 )
  {
    print "Updating $interfacesSConscript\n";
    open my $fh, ">>$interfacesSConscript";
    print $fh "baseEnv.buildit(\'$clInterfaceName\', [\'suse\'])\n";
  }
}

