// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LPSSALISTMGR_NOTIFYINTERFACEINPUTCHANNEL_H
#define LPSSALISTMGR_NOTIFYINTERFACEINPUTCHANNEL_H

#include <ais/interfaces/baseTypes/autogen_channel.h>

#include "NotifyInterface.hpp"

// LpsSaListMgrNotifyInterfaceInputChannel
DefineInputChannel(_, LpsSaListMgrNotifyInterface)

#endif // LPSSALISTMGR_NOTIFYINTERFACEINPUTCHANNEL_H

