// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LPSSALISTMGR_POSTINTERFACEINPUTCHANNEL_H
#define LPSSALISTMGR_POSTINTERFACEINPUTCHANNEL_H

#include <ais/interfaces/baseTypes/autogen_channel.h>

#include "PostInterface.hpp"

// LpsSaListMgrPostInterfaceInputChannel
DefineInputChannel(_, LpsSaListMgrPostInterface)

#endif // LPSSALISTMGR_POSTINTERFACEINPUTCHANNEL_H

