// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaJobMgrRespChannel_Channel_Output_H
#define LpsSaJobMgrRespChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaJobMgrRespChannel/LpsSaJobMgrRespChannel.h>

DefineOutputChannel(LpsSaJobMgrRespChannel.Channel.Output, LpsSaJobMgrRespChannel)

#endif

