#!/usr/bin/python
###############################################################################
## @file      SConscript
## @author    Bryan Salesky (bsalesky@rec.ri.cmu.edu)
## @date      May 16, 2008
## @brief     SConscript for the testTask application.
##
## @attention Copyright (C) 2008
## @attention National Robotics Engineering Center
## @attention Carnegie Mellon University
## @attention All rights reserved
## @attention Carnegie Mellon Proprietary
###############################################################################
Import( 'testEnv' )
testEnv.Append( LIBPATH = [ '#/apps/lib' ] )

testEnv.Append( CPPPATH = [ testEnv[ 'TES_COMMON_DIR' ] + '/protobuf/proto/' ] )

Command("TMAC_Telemetry_Transfer.pb.cc", 
        File(testEnv[ 'TES_COMMON_DIR'] + '/protobuf/proto/TMAC_Telemetry_Transfer.pb.cc').srcnode(), 
        Copy("$TARGET", "$SOURCE")) 

sourceFiles = [
    'LpsSaTotalsTelemetryTest.cpp',
    'TMAC_Telemetry_Transfer.pb.cc',   # Copied here to avoid scons collision
]

LpsSaTotalsTelemetryTest = testEnv.Program(
        target = 'LpsSaTotalsTelemetryTest',
        source = sourceFiles,
        LIBS = [ 'ais_task', 'ais_config', 'ais_log', 'protobuf',]
    )

testEnv.InstallBinary( LpsSaTotalsTelemetryTest )

testEnv.Alias("LpsSaTotalsTelemetryTest", "#bin/LpsSaTotalsTelemetryTest")


