// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaWeighRespChannel_Channel_Output_H
#define LpsSaWeighRespChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaWeighRespChannel/LpsSaWeighRespChannel.h>

DefineOutputChannel(LpsSaWeighRespChannel.Channel.Output, LpsSaWeighRespChannel)

#endif

