// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef WidgetsDebugData_Channel_Input_H
#define WidgetsDebugData_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/WidgetsDebugData/WidgetsDebugData.h>

DefineInputChannel(WidgetsDebugData.Channel.Input, WidgetsDebugData)

#endif

