// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'
#include "../../../WidgetsDebugData/Channel/Input/channel.h"

#include <ais/PluginProcessor/PluginDefine.h>

RegisterPlugin(WidgetsDebugData.Channel.Input, interfaces::Interface, WidgetsDebugDataInputChannel)
