// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaJobMgrDebugChannel_Channel_Output_H
#define LpsSaJobMgrDebugChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaJobMgrDebugChannel/LpsSaJobMgrDebugChannel.h>

DefineOutputChannel(LpsSaJobMgrDebugChannel.Channel.Output, LpsSaJobMgrDebugChannel)

#endif

