// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: CPMList.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_CPMList_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_CPMList_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/timestamp.pb.h"
#include "google/protobuf/wrappers.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_CPMList_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_CPMList_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_CPMList_2eproto;
namespace cat {
namespace cpm {
namespace list {
class List;
struct ListDefaultTypeInternal;
extern ListDefaultTypeInternal _List_default_instance_;
class List_Content;
struct List_ContentDefaultTypeInternal;
extern List_ContentDefaultTypeInternal _List_Content_default_instance_;
class List_Entry;
struct List_EntryDefaultTypeInternal;
extern List_EntryDefaultTypeInternal _List_Entry_default_instance_;
}  // namespace list
}  // namespace cpm
}  // namespace cat
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace cat {
namespace cpm {
namespace list {
enum List_TYPE : int {
  List_TYPE_INVALID = 0,
  List_TYPE_TRUCK = 1,
  List_TYPE_MATERIAL = 2,
  List_TYPE_CUSTOM1 = 3,
  List_TYPE_CUSTOM2 = 4,
  List_TYPE_CUSTOM3 = 5,
  List_TYPE_CUSTOM4 = 6,
  List_TYPE_List_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  List_TYPE_List_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool List_TYPE_IsValid(int value);
extern const uint32_t List_TYPE_internal_data_[];
constexpr List_TYPE List_TYPE_TYPE_MIN = static_cast<List_TYPE>(0);
constexpr List_TYPE List_TYPE_TYPE_MAX = static_cast<List_TYPE>(6);
constexpr int List_TYPE_TYPE_ARRAYSIZE = 6 + 1;
const ::google::protobuf::EnumDescriptor*
List_TYPE_descriptor();
template <typename T>
const std::string& List_TYPE_Name(T value) {
  static_assert(std::is_same<T, List_TYPE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to TYPE_Name().");
  return List_TYPE_Name(static_cast<List_TYPE>(value));
}
template <>
inline const std::string& List_TYPE_Name(List_TYPE value) {
  return ::google::protobuf::internal::NameOfDenseEnum<List_TYPE_descriptor,
                                                 0, 6>(
      static_cast<int>(value));
}
inline bool List_TYPE_Parse(absl::string_view name, List_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<List_TYPE>(
      List_TYPE_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class List_Entry final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cat.cpm.list.List.Entry) */ {
 public:
  inline List_Entry() : List_Entry(nullptr) {}
  ~List_Entry() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR List_Entry(
      ::google::protobuf::internal::ConstantInitialized);

  inline List_Entry(const List_Entry& from) : List_Entry(nullptr, from) {}
  inline List_Entry(List_Entry&& from) noexcept
      : List_Entry(nullptr, std::move(from)) {}
  inline List_Entry& operator=(const List_Entry& from) {
    CopyFrom(from);
    return *this;
  }
  inline List_Entry& operator=(List_Entry&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const List_Entry& default_instance() {
    return *internal_default_instance();
  }
  static inline const List_Entry* internal_default_instance() {
    return reinterpret_cast<const List_Entry*>(
        &_List_Entry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(List_Entry& a, List_Entry& b) { a.Swap(&b); }
  inline void Swap(List_Entry* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(List_Entry* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  List_Entry* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<List_Entry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const List_Entry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const List_Entry& from) { List_Entry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(List_Entry* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "cat.cpm.list.List.Entry"; }

 protected:
  explicit List_Entry(::google::protobuf::Arena* arena);
  List_Entry(::google::protobuf::Arena* arena, const List_Entry& from);
  List_Entry(::google::protobuf::Arena* arena, List_Entry&& from) noexcept
      : List_Entry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kIdFieldNumber = 2,
    kTargetWeightFieldNumber = 3,
    kDensityFieldNumber = 4,
  };
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // .google.protobuf.UInt32Value id = 2;
  bool has_id() const;
  void clear_id() ;
  const ::google::protobuf::UInt32Value& id() const;
  PROTOBUF_NODISCARD ::google::protobuf::UInt32Value* release_id();
  ::google::protobuf::UInt32Value* mutable_id();
  void set_allocated_id(::google::protobuf::UInt32Value* value);
  void unsafe_arena_set_allocated_id(::google::protobuf::UInt32Value* value);
  ::google::protobuf::UInt32Value* unsafe_arena_release_id();

  private:
  const ::google::protobuf::UInt32Value& _internal_id() const;
  ::google::protobuf::UInt32Value* _internal_mutable_id();

  public:
  // .google.protobuf.FloatValue target_weight = 3;
  bool has_target_weight() const;
  void clear_target_weight() ;
  const ::google::protobuf::FloatValue& target_weight() const;
  PROTOBUF_NODISCARD ::google::protobuf::FloatValue* release_target_weight();
  ::google::protobuf::FloatValue* mutable_target_weight();
  void set_allocated_target_weight(::google::protobuf::FloatValue* value);
  void unsafe_arena_set_allocated_target_weight(::google::protobuf::FloatValue* value);
  ::google::protobuf::FloatValue* unsafe_arena_release_target_weight();

  private:
  const ::google::protobuf::FloatValue& _internal_target_weight() const;
  ::google::protobuf::FloatValue* _internal_mutable_target_weight();

  public:
  // .google.protobuf.FloatValue density = 4;
  bool has_density() const;
  void clear_density() ;
  const ::google::protobuf::FloatValue& density() const;
  PROTOBUF_NODISCARD ::google::protobuf::FloatValue* release_density();
  ::google::protobuf::FloatValue* mutable_density();
  void set_allocated_density(::google::protobuf::FloatValue* value);
  void unsafe_arena_set_allocated_density(::google::protobuf::FloatValue* value);
  ::google::protobuf::FloatValue* unsafe_arena_release_density();

  private:
  const ::google::protobuf::FloatValue& _internal_density() const;
  ::google::protobuf::FloatValue* _internal_mutable_density();

  public:
  // @@protoc_insertion_point(class_scope:cat.cpm.list.List.Entry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 3,
      36, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_List_Entry_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const List_Entry& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::UInt32Value* id_;
    ::google::protobuf::FloatValue* target_weight_;
    ::google::protobuf::FloatValue* density_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CPMList_2eproto;
};
// -------------------------------------------------------------------

class List_Content final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cat.cpm.list.List.Content) */ {
 public:
  inline List_Content() : List_Content(nullptr) {}
  ~List_Content() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR List_Content(
      ::google::protobuf::internal::ConstantInitialized);

  inline List_Content(const List_Content& from) : List_Content(nullptr, from) {}
  inline List_Content(List_Content&& from) noexcept
      : List_Content(nullptr, std::move(from)) {}
  inline List_Content& operator=(const List_Content& from) {
    CopyFrom(from);
    return *this;
  }
  inline List_Content& operator=(List_Content&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const List_Content& default_instance() {
    return *internal_default_instance();
  }
  static inline const List_Content* internal_default_instance() {
    return reinterpret_cast<const List_Content*>(
        &_List_Content_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(List_Content& a, List_Content& b) { a.Swap(&b); }
  inline void Swap(List_Content* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(List_Content* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  List_Content* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<List_Content>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const List_Content& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const List_Content& from) { List_Content::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(List_Content* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "cat.cpm.list.List.Content"; }

 protected:
  explicit List_Content(::google::protobuf::Arena* arena);
  List_Content(::google::protobuf::Arena* arena, const List_Content& from);
  List_Content(::google::protobuf::Arena* arena, List_Content&& from) noexcept
      : List_Content(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEntriesFieldNumber = 2,
    kNameFieldNumber = 1,
  };
  // repeated .cat.cpm.list.List.Entry entries = 2;
  int entries_size() const;
  private:
  int _internal_entries_size() const;

  public:
  void clear_entries() ;
  ::cat::cpm::list::List_Entry* mutable_entries(int index);
  ::google::protobuf::RepeatedPtrField<::cat::cpm::list::List_Entry>* mutable_entries();

  private:
  const ::google::protobuf::RepeatedPtrField<::cat::cpm::list::List_Entry>& _internal_entries() const;
  ::google::protobuf::RepeatedPtrField<::cat::cpm::list::List_Entry>* _internal_mutable_entries();
  public:
  const ::cat::cpm::list::List_Entry& entries(int index) const;
  ::cat::cpm::list::List_Entry* add_entries();
  const ::google::protobuf::RepeatedPtrField<::cat::cpm::list::List_Entry>& entries() const;
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // @@protoc_insertion_point(class_scope:cat.cpm.list.List.Content)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      38, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_List_Content_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const List_Content& from_msg);
    ::google::protobuf::RepeatedPtrField< ::cat::cpm::list::List_Entry > entries_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CPMList_2eproto;
};
// -------------------------------------------------------------------

class List final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cat.cpm.list.List) */ {
 public:
  inline List() : List(nullptr) {}
  ~List() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR List(
      ::google::protobuf::internal::ConstantInitialized);

  inline List(const List& from) : List(nullptr, from) {}
  inline List(List&& from) noexcept
      : List(nullptr, std::move(from)) {}
  inline List& operator=(const List& from) {
    CopyFrom(from);
    return *this;
  }
  inline List& operator=(List&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const List& default_instance() {
    return *internal_default_instance();
  }
  static inline const List* internal_default_instance() {
    return reinterpret_cast<const List*>(
        &_List_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(List& a, List& b) { a.Swap(&b); }
  inline void Swap(List* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(List* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  List* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<List>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const List& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const List& from) { List::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(List* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "cat.cpm.list.List"; }

 protected:
  explicit List(::google::protobuf::Arena* arena);
  List(::google::protobuf::Arena* arena, const List& from);
  List(::google::protobuf::Arena* arena, List&& from) noexcept
      : List(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Entry = List_Entry;
  using Content = List_Content;
  using TYPE = List_TYPE;
  static constexpr TYPE INVALID = List_TYPE_INVALID;
  static constexpr TYPE TRUCK = List_TYPE_TRUCK;
  static constexpr TYPE MATERIAL = List_TYPE_MATERIAL;
  static constexpr TYPE CUSTOM1 = List_TYPE_CUSTOM1;
  static constexpr TYPE CUSTOM2 = List_TYPE_CUSTOM2;
  static constexpr TYPE CUSTOM3 = List_TYPE_CUSTOM3;
  static constexpr TYPE CUSTOM4 = List_TYPE_CUSTOM4;
  static inline bool TYPE_IsValid(int value) {
    return List_TYPE_IsValid(value);
  }
  static constexpr TYPE TYPE_MIN = List_TYPE_TYPE_MIN;
  static constexpr TYPE TYPE_MAX = List_TYPE_TYPE_MAX;
  static constexpr int TYPE_ARRAYSIZE = List_TYPE_TYPE_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* TYPE_descriptor() {
    return List_TYPE_descriptor();
  }
  template <typename T>
  static inline const std::string& TYPE_Name(T value) {
    return List_TYPE_Name(value);
  }
  static inline bool TYPE_Parse(absl::string_view name, TYPE* value) {
    return List_TYPE_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kRevisionFieldNumber = 2,
    kContentFieldNumber = 3,
    kTypeFieldNumber = 1,
    kMaxListLengthFieldNumber = 4,
    kMaxNameLengthFieldNumber = 5,
  };
  // .google.protobuf.Timestamp revision = 2;
  bool has_revision() const;
  void clear_revision() ;
  const ::google::protobuf::Timestamp& revision() const;
  PROTOBUF_NODISCARD ::google::protobuf::Timestamp* release_revision();
  ::google::protobuf::Timestamp* mutable_revision();
  void set_allocated_revision(::google::protobuf::Timestamp* value);
  void unsafe_arena_set_allocated_revision(::google::protobuf::Timestamp* value);
  ::google::protobuf::Timestamp* unsafe_arena_release_revision();

  private:
  const ::google::protobuf::Timestamp& _internal_revision() const;
  ::google::protobuf::Timestamp* _internal_mutable_revision();

  public:
  // .cat.cpm.list.List.Content content = 3;
  bool has_content() const;
  void clear_content() ;
  const ::cat::cpm::list::List_Content& content() const;
  PROTOBUF_NODISCARD ::cat::cpm::list::List_Content* release_content();
  ::cat::cpm::list::List_Content* mutable_content();
  void set_allocated_content(::cat::cpm::list::List_Content* value);
  void unsafe_arena_set_allocated_content(::cat::cpm::list::List_Content* value);
  ::cat::cpm::list::List_Content* unsafe_arena_release_content();

  private:
  const ::cat::cpm::list::List_Content& _internal_content() const;
  ::cat::cpm::list::List_Content* _internal_mutable_content();

  public:
  // .cat.cpm.list.List.TYPE type = 1;
  void clear_type() ;
  ::cat::cpm::list::List_TYPE type() const;
  void set_type(::cat::cpm::list::List_TYPE value);

  private:
  ::cat::cpm::list::List_TYPE _internal_type() const;
  void _internal_set_type(::cat::cpm::list::List_TYPE value);

  public:
  // uint32 max_list_length = 4;
  void clear_max_list_length() ;
  ::uint32_t max_list_length() const;
  void set_max_list_length(::uint32_t value);

  private:
  ::uint32_t _internal_max_list_length() const;
  void _internal_set_max_list_length(::uint32_t value);

  public:
  // uint32 max_name_length = 5;
  void clear_max_name_length() ;
  ::uint32_t max_name_length() const;
  void set_max_name_length(::uint32_t value);

  private:
  ::uint32_t _internal_max_name_length() const;
  void _internal_set_max_name_length(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:cat.cpm.list.List)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_List_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const List& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::Timestamp* revision_;
    ::cat::cpm::list::List_Content* content_;
    int type_;
    ::uint32_t max_list_length_;
    ::uint32_t max_name_length_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CPMList_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// List_Entry

// string name = 1;
inline void List_Entry::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& List_Entry::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cat.cpm.list.List.Entry.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void List_Entry::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cat.cpm.list.List.Entry.name)
}
inline std::string* List_Entry::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:cat.cpm.list.List.Entry.name)
  return _s;
}
inline const std::string& List_Entry::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void List_Entry::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* List_Entry::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* List_Entry::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cat.cpm.list.List.Entry.name)
  return _impl_.name_.Release();
}
inline void List_Entry::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cat.cpm.list.List.Entry.name)
}

// .google.protobuf.UInt32Value id = 2;
inline bool List_Entry::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.id_ != nullptr);
  return value;
}
inline const ::google::protobuf::UInt32Value& List_Entry::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::UInt32Value* p = _impl_.id_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::UInt32Value&>(::google::protobuf::_UInt32Value_default_instance_);
}
inline const ::google::protobuf::UInt32Value& List_Entry::id() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cat.cpm.list.List.Entry.id)
  return _internal_id();
}
inline void List_Entry::unsafe_arena_set_allocated_id(::google::protobuf::UInt32Value* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.id_);
  }
  _impl_.id_ = reinterpret_cast<::google::protobuf::UInt32Value*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cat.cpm.list.List.Entry.id)
}
inline ::google::protobuf::UInt32Value* List_Entry::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::UInt32Value* released = _impl_.id_;
  _impl_.id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::google::protobuf::UInt32Value* List_Entry::unsafe_arena_release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cat.cpm.list.List.Entry.id)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::UInt32Value* temp = _impl_.id_;
  _impl_.id_ = nullptr;
  return temp;
}
inline ::google::protobuf::UInt32Value* List_Entry::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.id_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::UInt32Value>(GetArena());
    _impl_.id_ = reinterpret_cast<::google::protobuf::UInt32Value*>(p);
  }
  return _impl_.id_;
}
inline ::google::protobuf::UInt32Value* List_Entry::mutable_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::google::protobuf::UInt32Value* _msg = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:cat.cpm.list.List.Entry.id)
  return _msg;
}
inline void List_Entry::set_allocated_id(::google::protobuf::UInt32Value* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.id_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.id_ = reinterpret_cast<::google::protobuf::UInt32Value*>(value);
  // @@protoc_insertion_point(field_set_allocated:cat.cpm.list.List.Entry.id)
}

// .google.protobuf.FloatValue target_weight = 3;
inline bool List_Entry::has_target_weight() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.target_weight_ != nullptr);
  return value;
}
inline const ::google::protobuf::FloatValue& List_Entry::_internal_target_weight() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::FloatValue* p = _impl_.target_weight_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::FloatValue&>(::google::protobuf::_FloatValue_default_instance_);
}
inline const ::google::protobuf::FloatValue& List_Entry::target_weight() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cat.cpm.list.List.Entry.target_weight)
  return _internal_target_weight();
}
inline void List_Entry::unsafe_arena_set_allocated_target_weight(::google::protobuf::FloatValue* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.target_weight_);
  }
  _impl_.target_weight_ = reinterpret_cast<::google::protobuf::FloatValue*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cat.cpm.list.List.Entry.target_weight)
}
inline ::google::protobuf::FloatValue* List_Entry::release_target_weight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::google::protobuf::FloatValue* released = _impl_.target_weight_;
  _impl_.target_weight_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::google::protobuf::FloatValue* List_Entry::unsafe_arena_release_target_weight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cat.cpm.list.List.Entry.target_weight)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::google::protobuf::FloatValue* temp = _impl_.target_weight_;
  _impl_.target_weight_ = nullptr;
  return temp;
}
inline ::google::protobuf::FloatValue* List_Entry::_internal_mutable_target_weight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.target_weight_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::FloatValue>(GetArena());
    _impl_.target_weight_ = reinterpret_cast<::google::protobuf::FloatValue*>(p);
  }
  return _impl_.target_weight_;
}
inline ::google::protobuf::FloatValue* List_Entry::mutable_target_weight() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::google::protobuf::FloatValue* _msg = _internal_mutable_target_weight();
  // @@protoc_insertion_point(field_mutable:cat.cpm.list.List.Entry.target_weight)
  return _msg;
}
inline void List_Entry::set_allocated_target_weight(::google::protobuf::FloatValue* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.target_weight_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.target_weight_ = reinterpret_cast<::google::protobuf::FloatValue*>(value);
  // @@protoc_insertion_point(field_set_allocated:cat.cpm.list.List.Entry.target_weight)
}

// .google.protobuf.FloatValue density = 4;
inline bool List_Entry::has_density() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.density_ != nullptr);
  return value;
}
inline const ::google::protobuf::FloatValue& List_Entry::_internal_density() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::FloatValue* p = _impl_.density_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::FloatValue&>(::google::protobuf::_FloatValue_default_instance_);
}
inline const ::google::protobuf::FloatValue& List_Entry::density() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cat.cpm.list.List.Entry.density)
  return _internal_density();
}
inline void List_Entry::unsafe_arena_set_allocated_density(::google::protobuf::FloatValue* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.density_);
  }
  _impl_.density_ = reinterpret_cast<::google::protobuf::FloatValue*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cat.cpm.list.List.Entry.density)
}
inline ::google::protobuf::FloatValue* List_Entry::release_density() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::google::protobuf::FloatValue* released = _impl_.density_;
  _impl_.density_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::google::protobuf::FloatValue* List_Entry::unsafe_arena_release_density() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cat.cpm.list.List.Entry.density)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::google::protobuf::FloatValue* temp = _impl_.density_;
  _impl_.density_ = nullptr;
  return temp;
}
inline ::google::protobuf::FloatValue* List_Entry::_internal_mutable_density() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.density_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::FloatValue>(GetArena());
    _impl_.density_ = reinterpret_cast<::google::protobuf::FloatValue*>(p);
  }
  return _impl_.density_;
}
inline ::google::protobuf::FloatValue* List_Entry::mutable_density() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::google::protobuf::FloatValue* _msg = _internal_mutable_density();
  // @@protoc_insertion_point(field_mutable:cat.cpm.list.List.Entry.density)
  return _msg;
}
inline void List_Entry::set_allocated_density(::google::protobuf::FloatValue* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.density_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.density_ = reinterpret_cast<::google::protobuf::FloatValue*>(value);
  // @@protoc_insertion_point(field_set_allocated:cat.cpm.list.List.Entry.density)
}

// -------------------------------------------------------------------

// List_Content

// string name = 1;
inline void List_Content::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& List_Content::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cat.cpm.list.List.Content.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void List_Content::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cat.cpm.list.List.Content.name)
}
inline std::string* List_Content::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:cat.cpm.list.List.Content.name)
  return _s;
}
inline const std::string& List_Content::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void List_Content::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* List_Content::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* List_Content::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cat.cpm.list.List.Content.name)
  return _impl_.name_.Release();
}
inline void List_Content::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cat.cpm.list.List.Content.name)
}

// repeated .cat.cpm.list.List.Entry entries = 2;
inline int List_Content::_internal_entries_size() const {
  return _internal_entries().size();
}
inline int List_Content::entries_size() const {
  return _internal_entries_size();
}
inline void List_Content::clear_entries() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entries_.Clear();
}
inline ::cat::cpm::list::List_Entry* List_Content::mutable_entries(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:cat.cpm.list.List.Content.entries)
  return _internal_mutable_entries()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::cat::cpm::list::List_Entry>* List_Content::mutable_entries()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:cat.cpm.list.List.Content.entries)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_entries();
}
inline const ::cat::cpm::list::List_Entry& List_Content::entries(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cat.cpm.list.List.Content.entries)
  return _internal_entries().Get(index);
}
inline ::cat::cpm::list::List_Entry* List_Content::add_entries() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::cat::cpm::list::List_Entry* _add = _internal_mutable_entries()->Add();
  // @@protoc_insertion_point(field_add:cat.cpm.list.List.Content.entries)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::cat::cpm::list::List_Entry>& List_Content::entries() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:cat.cpm.list.List.Content.entries)
  return _internal_entries();
}
inline const ::google::protobuf::RepeatedPtrField<::cat::cpm::list::List_Entry>&
List_Content::_internal_entries() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.entries_;
}
inline ::google::protobuf::RepeatedPtrField<::cat::cpm::list::List_Entry>*
List_Content::_internal_mutable_entries() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.entries_;
}

// -------------------------------------------------------------------

// List

// .cat.cpm.list.List.TYPE type = 1;
inline void List::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::cat::cpm::list::List_TYPE List::type() const {
  // @@protoc_insertion_point(field_get:cat.cpm.list.List.type)
  return _internal_type();
}
inline void List::set_type(::cat::cpm::list::List_TYPE value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:cat.cpm.list.List.type)
}
inline ::cat::cpm::list::List_TYPE List::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::cat::cpm::list::List_TYPE>(_impl_.type_);
}
inline void List::_internal_set_type(::cat::cpm::list::List_TYPE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// .google.protobuf.Timestamp revision = 2;
inline bool List::has_revision() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.revision_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& List::_internal_revision() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.revision_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& List::revision() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cat.cpm.list.List.revision)
  return _internal_revision();
}
inline void List::unsafe_arena_set_allocated_revision(::google::protobuf::Timestamp* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.revision_);
  }
  _impl_.revision_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cat.cpm.list.List.revision)
}
inline ::google::protobuf::Timestamp* List::release_revision() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* released = _impl_.revision_;
  _impl_.revision_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::google::protobuf::Timestamp* List::unsafe_arena_release_revision() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cat.cpm.list.List.revision)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* temp = _impl_.revision_;
  _impl_.revision_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* List::_internal_mutable_revision() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.revision_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.revision_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.revision_;
}
inline ::google::protobuf::Timestamp* List::mutable_revision() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::google::protobuf::Timestamp* _msg = _internal_mutable_revision();
  // @@protoc_insertion_point(field_mutable:cat.cpm.list.List.revision)
  return _msg;
}
inline void List::set_allocated_revision(::google::protobuf::Timestamp* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.revision_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.revision_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:cat.cpm.list.List.revision)
}

// .cat.cpm.list.List.Content content = 3;
inline bool List::has_content() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.content_ != nullptr);
  return value;
}
inline void List::clear_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.content_ != nullptr) _impl_.content_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::cat::cpm::list::List_Content& List::_internal_content() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::cat::cpm::list::List_Content* p = _impl_.content_;
  return p != nullptr ? *p : reinterpret_cast<const ::cat::cpm::list::List_Content&>(::cat::cpm::list::_List_Content_default_instance_);
}
inline const ::cat::cpm::list::List_Content& List::content() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cat.cpm.list.List.content)
  return _internal_content();
}
inline void List::unsafe_arena_set_allocated_content(::cat::cpm::list::List_Content* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.content_);
  }
  _impl_.content_ = reinterpret_cast<::cat::cpm::list::List_Content*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cat.cpm.list.List.content)
}
inline ::cat::cpm::list::List_Content* List::release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::cat::cpm::list::List_Content* released = _impl_.content_;
  _impl_.content_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::cat::cpm::list::List_Content* List::unsafe_arena_release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cat.cpm.list.List.content)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::cat::cpm::list::List_Content* temp = _impl_.content_;
  _impl_.content_ = nullptr;
  return temp;
}
inline ::cat::cpm::list::List_Content* List::_internal_mutable_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.content_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::cat::cpm::list::List_Content>(GetArena());
    _impl_.content_ = reinterpret_cast<::cat::cpm::list::List_Content*>(p);
  }
  return _impl_.content_;
}
inline ::cat::cpm::list::List_Content* List::mutable_content() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::cat::cpm::list::List_Content* _msg = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:cat.cpm.list.List.content)
  return _msg;
}
inline void List::set_allocated_content(::cat::cpm::list::List_Content* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.content_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.content_ = reinterpret_cast<::cat::cpm::list::List_Content*>(value);
  // @@protoc_insertion_point(field_set_allocated:cat.cpm.list.List.content)
}

// uint32 max_list_length = 4;
inline void List::clear_max_list_length() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_list_length_ = 0u;
}
inline ::uint32_t List::max_list_length() const {
  // @@protoc_insertion_point(field_get:cat.cpm.list.List.max_list_length)
  return _internal_max_list_length();
}
inline void List::set_max_list_length(::uint32_t value) {
  _internal_set_max_list_length(value);
  // @@protoc_insertion_point(field_set:cat.cpm.list.List.max_list_length)
}
inline ::uint32_t List::_internal_max_list_length() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_list_length_;
}
inline void List::_internal_set_max_list_length(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_list_length_ = value;
}

// uint32 max_name_length = 5;
inline void List::clear_max_name_length() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_name_length_ = 0u;
}
inline ::uint32_t List::max_name_length() const {
  // @@protoc_insertion_point(field_get:cat.cpm.list.List.max_name_length)
  return _internal_max_name_length();
}
inline void List::set_max_name_length(::uint32_t value) {
  _internal_set_max_name_length(value);
  // @@protoc_insertion_point(field_set:cat.cpm.list.List.max_name_length)
}
inline ::uint32_t List::_internal_max_name_length() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_name_length_;
}
inline void List::_internal_set_max_name_length(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_name_length_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace list
}  // namespace cpm
}  // namespace cat


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::cat::cpm::list::List_TYPE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::cat::cpm::list::List_TYPE>() {
  return ::cat::cpm::list::List_TYPE_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_CPMList_2eproto_2epb_2eh
