// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: CPMList.proto
// Protobuf C++ Version: 5.27.0

#include "CPMList.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace cat {
namespace cpm {
namespace list {

inline constexpr List_Entry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{nullptr},
        target_weight_{nullptr},
        density_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR List_Entry::List_Entry(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct List_EntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR List_EntryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~List_EntryDefaultTypeInternal() {}
  union {
    List_Entry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 List_EntryDefaultTypeInternal _List_Entry_default_instance_;

inline constexpr List_Content::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : entries_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR List_Content::List_Content(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct List_ContentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR List_ContentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~List_ContentDefaultTypeInternal() {}
  union {
    List_Content _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 List_ContentDefaultTypeInternal _List_Content_default_instance_;

inline constexpr List::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        revision_{nullptr},
        content_{nullptr},
        type_{static_cast< ::cat::cpm::list::List_TYPE >(0)},
        max_list_length_{0u},
        max_name_length_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR List::List(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListDefaultTypeInternal() {}
  union {
    List _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListDefaultTypeInternal _List_default_instance_;
}  // namespace list
}  // namespace cpm
}  // namespace cat
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_CPMList_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_CPMList_2eproto = nullptr;
const ::uint32_t
    TableStruct_CPMList_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List_Entry, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List_Entry, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List_Entry, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List_Entry, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List_Entry, _impl_.target_weight_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List_Entry, _impl_.density_),
        ~0u,
        0,
        1,
        2,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List_Content, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List_Content, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List_Content, _impl_.entries_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List, _impl_.revision_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List, _impl_.content_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List, _impl_.max_list_length_),
        PROTOBUF_FIELD_OFFSET(::cat::cpm::list::List, _impl_.max_name_length_),
        ~0u,
        0,
        1,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::cat::cpm::list::List_Entry)},
        {16, -1, -1, sizeof(::cat::cpm::list::List_Content)},
        {26, 39, -1, sizeof(::cat::cpm::list::List)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::cat::cpm::list::_List_Entry_default_instance_._instance,
    &::cat::cpm::list::_List_Content_default_instance_._instance,
    &::cat::cpm::list::_List_default_instance_._instance,
};
const char descriptor_table_protodef_CPMList_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rCPMList.proto\022\014cat.cpm.list\032\037google/pr"
    "otobuf/timestamp.proto\032\036google/protobuf/"
    "wrappers.proto\"\204\004\n\004List\022%\n\004type\030\001 \001(\0162\027."
    "cat.cpm.list.List.TYPE\022,\n\010revision\030\002 \001(\013"
    "2\032.google.protobuf.Timestamp\022+\n\007content\030"
    "\003 \001(\0132\032.cat.cpm.list.List.Content\022\027\n\017max"
    "_list_length\030\004 \001(\r\022\027\n\017max_name_length\030\005 "
    "\001(\r\032\241\001\n\005Entry\022\014\n\004name\030\001 \001(\t\022(\n\002id\030\002 \001(\0132"
    "\034.google.protobuf.UInt32Value\0222\n\rtarget_"
    "weight\030\003 \001(\0132\033.google.protobuf.FloatValu"
    "e\022,\n\007density\030\004 \001(\0132\033.google.protobuf.Flo"
    "atValue\032B\n\007Content\022\014\n\004name\030\001 \001(\t\022)\n\007entr"
    "ies\030\002 \003(\0132\030.cat.cpm.list.List.Entry\"`\n\004T"
    "YPE\022\013\n\007INVALID\020\000\022\t\n\005TRUCK\020\001\022\014\n\010MATERIAL\020"
    "\002\022\013\n\007CUSTOM1\020\003\022\013\n\007CUSTOM2\020\004\022\013\n\007CUSTOM3\020\005"
    "\022\013\n\007CUSTOM4\020\006b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_CPMList_2eproto_deps[2] =
    {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
        &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
};
static ::absl::once_flag descriptor_table_CPMList_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_CPMList_2eproto = {
    false,
    false,
    621,
    descriptor_table_protodef_CPMList_2eproto,
    "CPMList.proto",
    &descriptor_table_CPMList_2eproto_once,
    descriptor_table_CPMList_2eproto_deps,
    2,
    3,
    schemas,
    file_default_instances,
    TableStruct_CPMList_2eproto::offsets,
    file_level_enum_descriptors_CPMList_2eproto,
    file_level_service_descriptors_CPMList_2eproto,
};
namespace cat {
namespace cpm {
namespace list {
const ::google::protobuf::EnumDescriptor* List_TYPE_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_CPMList_2eproto);
  return file_level_enum_descriptors_CPMList_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t List_TYPE_internal_data_[] = {
    458752u, 0u, };
bool List_TYPE_IsValid(int value) {
  return 0 <= value && value <= 6;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr List_TYPE List::INVALID;
constexpr List_TYPE List::TRUCK;
constexpr List_TYPE List::MATERIAL;
constexpr List_TYPE List::CUSTOM1;
constexpr List_TYPE List::CUSTOM2;
constexpr List_TYPE List::CUSTOM3;
constexpr List_TYPE List::CUSTOM4;
constexpr List_TYPE List::TYPE_MIN;
constexpr List_TYPE List::TYPE_MAX;
constexpr int List::TYPE_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class List_Entry::_Internal {
 public:
  using HasBits =
      decltype(std::declval<List_Entry>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(List_Entry, _impl_._has_bits_);
};

void List_Entry::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.id_ != nullptr) _impl_.id_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void List_Entry::clear_target_weight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.target_weight_ != nullptr) _impl_.target_weight_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void List_Entry::clear_density() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.density_ != nullptr) _impl_.density_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
List_Entry::List_Entry(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cat.cpm.list.List.Entry)
}
inline PROTOBUF_NDEBUG_INLINE List_Entry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cat::cpm::list::List_Entry& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

List_Entry::List_Entry(
    ::google::protobuf::Arena* arena,
    const List_Entry& from)
    : ::google::protobuf::Message(arena) {
  List_Entry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.id_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::UInt32Value>(
                              arena, *from._impl_.id_)
                        : nullptr;
  _impl_.target_weight_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(
                              arena, *from._impl_.target_weight_)
                        : nullptr;
  _impl_.density_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(
                              arena, *from._impl_.density_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:cat.cpm.list.List.Entry)
}
inline PROTOBUF_NDEBUG_INLINE List_Entry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena) {}

inline void List_Entry::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, density_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::density_));
}
List_Entry::~List_Entry() {
  // @@protoc_insertion_point(destructor:cat.cpm.list.List.Entry)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void List_Entry::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  delete _impl_.id_;
  delete _impl_.target_weight_;
  delete _impl_.density_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
List_Entry::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(List_Entry, _impl_._cached_size_),
              false,
          },
          &List_Entry::MergeImpl,
          &List_Entry::kDescriptorMethods,
          &descriptor_table_CPMList_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 3, 36, 2> List_Entry::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(List_Entry, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_List_Entry_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cat::cpm::list::List_Entry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .google.protobuf.FloatValue density = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 2, 2, PROTOBUF_FIELD_OFFSET(List_Entry, _impl_.density_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(List_Entry, _impl_.name_)}},
    // .google.protobuf.UInt32Value id = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(List_Entry, _impl_.id_)}},
    // .google.protobuf.FloatValue target_weight = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(List_Entry, _impl_.target_weight_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(List_Entry, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.UInt32Value id = 2;
    {PROTOBUF_FIELD_OFFSET(List_Entry, _impl_.id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.FloatValue target_weight = 3;
    {PROTOBUF_FIELD_OFFSET(List_Entry, _impl_.target_weight_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.FloatValue density = 4;
    {PROTOBUF_FIELD_OFFSET(List_Entry, _impl_.density_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::UInt32Value>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::FloatValue>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::FloatValue>()},
  }}, {{
    "\27\4\0\0\0\0\0\0"
    "cat.cpm.list.List.Entry"
    "name"
  }},
};

PROTOBUF_NOINLINE void List_Entry::Clear() {
// @@protoc_insertion_point(message_clear_start:cat.cpm.list.List.Entry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.id_ != nullptr);
      _impl_.id_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.target_weight_ != nullptr);
      _impl_.target_weight_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.density_ != nullptr);
      _impl_.density_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* List_Entry::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cat.cpm.list.List.Entry)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cat.cpm.list.List.Entry.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.UInt32Value id = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.id_, _impl_.id_->GetCachedSize(), target, stream);
  }

  // .google.protobuf.FloatValue target_weight = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.target_weight_, _impl_.target_weight_->GetCachedSize(), target, stream);
  }

  // .google.protobuf.FloatValue density = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *_impl_.density_, _impl_.density_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cat.cpm.list.List.Entry)
  return target;
}

::size_t List_Entry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cat.cpm.list.List.Entry)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // .google.protobuf.UInt32Value id = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.id_);
    }

    // .google.protobuf.FloatValue target_weight = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.target_weight_);
    }

    // .google.protobuf.FloatValue density = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.density_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void List_Entry::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<List_Entry*>(&to_msg);
  auto& from = static_cast<const List_Entry&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:cat.cpm.list.List.Entry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.id_ != nullptr);
      if (_this->_impl_.id_ == nullptr) {
        _this->_impl_.id_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::UInt32Value>(arena, *from._impl_.id_);
      } else {
        _this->_impl_.id_->MergeFrom(*from._impl_.id_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.target_weight_ != nullptr);
      if (_this->_impl_.target_weight_ == nullptr) {
        _this->_impl_.target_weight_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(arena, *from._impl_.target_weight_);
      } else {
        _this->_impl_.target_weight_->MergeFrom(*from._impl_.target_weight_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.density_ != nullptr);
      if (_this->_impl_.density_ == nullptr) {
        _this->_impl_.density_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::FloatValue>(arena, *from._impl_.density_);
      } else {
        _this->_impl_.density_->MergeFrom(*from._impl_.density_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void List_Entry::CopyFrom(const List_Entry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cat.cpm.list.List.Entry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void List_Entry::InternalSwap(List_Entry* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(List_Entry, _impl_.density_)
      + sizeof(List_Entry::_impl_.density_)
      - PROTOBUF_FIELD_OFFSET(List_Entry, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata List_Entry::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class List_Content::_Internal {
 public:
};

List_Content::List_Content(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cat.cpm.list.List.Content)
}
inline PROTOBUF_NDEBUG_INLINE List_Content::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cat::cpm::list::List_Content& from_msg)
      : entries_{visibility, arena, from.entries_},
        name_(arena, from.name_),
        _cached_size_{0} {}

List_Content::List_Content(
    ::google::protobuf::Arena* arena,
    const List_Content& from)
    : ::google::protobuf::Message(arena) {
  List_Content* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:cat.cpm.list.List.Content)
}
inline PROTOBUF_NDEBUG_INLINE List_Content::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : entries_{visibility, arena},
        name_(arena),
        _cached_size_{0} {}

inline void List_Content::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
List_Content::~List_Content() {
  // @@protoc_insertion_point(destructor:cat.cpm.list.List.Content)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void List_Content::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
List_Content::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(List_Content, _impl_._cached_size_),
              false,
          },
          &List_Content::MergeImpl,
          &List_Content::kDescriptorMethods,
          &descriptor_table_CPMList_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 38, 2> List_Content::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_List_Content_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cat::cpm::list::List_Content>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .cat.cpm.list.List.Entry entries = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(List_Content, _impl_.entries_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(List_Content, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(List_Content, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .cat.cpm.list.List.Entry entries = 2;
    {PROTOBUF_FIELD_OFFSET(List_Content, _impl_.entries_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::cat::cpm::list::List_Entry>()},
  }}, {{
    "\31\4\0\0\0\0\0\0"
    "cat.cpm.list.List.Content"
    "name"
  }},
};

PROTOBUF_NOINLINE void List_Content::Clear() {
// @@protoc_insertion_point(message_clear_start:cat.cpm.list.List.Content)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.entries_.Clear();
  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* List_Content::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cat.cpm.list.List.Content)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cat.cpm.list.List.Content.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated .cat.cpm.list.List.Entry entries = 2;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_entries_size());
       i < n; i++) {
    const auto& repfield = this->_internal_entries().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            2, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cat.cpm.list.List.Content)
  return target;
}

::size_t List_Content::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cat.cpm.list.List.Content)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .cat.cpm.list.List.Entry entries = 2;
  total_size += 1UL * this->_internal_entries_size();
  for (const auto& msg : this->_internal_entries()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void List_Content::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<List_Content*>(&to_msg);
  auto& from = static_cast<const List_Content&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cat.cpm.list.List.Content)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_entries()->MergeFrom(
      from._internal_entries());
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void List_Content::CopyFrom(const List_Content& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cat.cpm.list.List.Content)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void List_Content::InternalSwap(List_Content* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.entries_.InternalSwap(&other->_impl_.entries_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata List_Content::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class List::_Internal {
 public:
  using HasBits =
      decltype(std::declval<List>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(List, _impl_._has_bits_);
};

void List::clear_revision() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.revision_ != nullptr) _impl_.revision_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
List::List(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cat.cpm.list.List)
}
inline PROTOBUF_NDEBUG_INLINE List::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cat::cpm::list::List& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

List::List(
    ::google::protobuf::Arena* arena,
    const List& from)
    : ::google::protobuf::Message(arena) {
  List* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.revision_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(
                              arena, *from._impl_.revision_)
                        : nullptr;
  _impl_.content_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::cat::cpm::list::List_Content>(
                              arena, *from._impl_.content_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, max_name_length_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::max_name_length_));

  // @@protoc_insertion_point(copy_constructor:cat.cpm.list.List)
}
inline PROTOBUF_NDEBUG_INLINE List::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void List::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, revision_),
           0,
           offsetof(Impl_, max_name_length_) -
               offsetof(Impl_, revision_) +
               sizeof(Impl_::max_name_length_));
}
List::~List() {
  // @@protoc_insertion_point(destructor:cat.cpm.list.List)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void List::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.revision_;
  delete _impl_.content_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
List::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(List, _impl_._cached_size_),
              false,
          },
          &List::MergeImpl,
          &List::kDescriptorMethods,
          &descriptor_table_CPMList_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 0, 2> List::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(List, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_List_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cat::cpm::list::List>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .cat.cpm.list.List.TYPE type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(List, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(List, _impl_.type_)}},
    // .google.protobuf.Timestamp revision = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(List, _impl_.revision_)}},
    // .cat.cpm.list.List.Content content = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(List, _impl_.content_)}},
    // uint32 max_list_length = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(List, _impl_.max_list_length_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(List, _impl_.max_list_length_)}},
    // uint32 max_name_length = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(List, _impl_.max_name_length_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(List, _impl_.max_name_length_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .cat.cpm.list.List.TYPE type = 1;
    {PROTOBUF_FIELD_OFFSET(List, _impl_.type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .google.protobuf.Timestamp revision = 2;
    {PROTOBUF_FIELD_OFFSET(List, _impl_.revision_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .cat.cpm.list.List.Content content = 3;
    {PROTOBUF_FIELD_OFFSET(List, _impl_.content_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint32 max_list_length = 4;
    {PROTOBUF_FIELD_OFFSET(List, _impl_.max_list_length_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 max_name_length = 5;
    {PROTOBUF_FIELD_OFFSET(List, _impl_.max_name_length_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
    {::_pbi::TcParser::GetTable<::cat::cpm::list::List_Content>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void List::Clear() {
// @@protoc_insertion_point(message_clear_start:cat.cpm.list.List)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.revision_ != nullptr);
      _impl_.revision_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.content_ != nullptr);
      _impl_.content_->Clear();
    }
  }
  ::memset(&_impl_.type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.max_name_length_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.max_name_length_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* List::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cat.cpm.list.List)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .cat.cpm.list.List.TYPE type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_type(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Timestamp revision = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.revision_, _impl_.revision_->GetCachedSize(), target, stream);
  }

  // .cat.cpm.list.List.Content content = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.content_, _impl_.content_->GetCachedSize(), target, stream);
  }

  // uint32 max_list_length = 4;
  if (this->_internal_max_list_length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_max_list_length(), target);
  }

  // uint32 max_name_length = 5;
  if (this->_internal_max_name_length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_max_name_length(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cat.cpm.list.List)
  return target;
}

::size_t List::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cat.cpm.list.List)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .google.protobuf.Timestamp revision = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.revision_);
    }

    // .cat.cpm.list.List.Content content = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.content_);
    }

  }
  // .cat.cpm.list.List.TYPE type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // uint32 max_list_length = 4;
  if (this->_internal_max_list_length() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_max_list_length());
  }

  // uint32 max_name_length = 5;
  if (this->_internal_max_name_length() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_max_name_length());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void List::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<List*>(&to_msg);
  auto& from = static_cast<const List&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:cat.cpm.list.List)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.revision_ != nullptr);
      if (_this->_impl_.revision_ == nullptr) {
        _this->_impl_.revision_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(arena, *from._impl_.revision_);
      } else {
        _this->_impl_.revision_->MergeFrom(*from._impl_.revision_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.content_ != nullptr);
      if (_this->_impl_.content_ == nullptr) {
        _this->_impl_.content_ =
            ::google::protobuf::Message::CopyConstruct<::cat::cpm::list::List_Content>(arena, *from._impl_.content_);
      } else {
        _this->_impl_.content_->MergeFrom(*from._impl_.content_);
      }
    }
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (from._internal_max_list_length() != 0) {
    _this->_impl_.max_list_length_ = from._impl_.max_list_length_;
  }
  if (from._internal_max_name_length() != 0) {
    _this->_impl_.max_name_length_ = from._impl_.max_name_length_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void List::CopyFrom(const List& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cat.cpm.list.List)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void List::InternalSwap(List* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(List, _impl_.max_name_length_)
      + sizeof(List::_impl_.max_name_length_)
      - PROTOBUF_FIELD_OFFSET(List, _impl_.revision_)>(
          reinterpret_cast<char*>(&_impl_.revision_),
          reinterpret_cast<char*>(&other->_impl_.revision_));
}

::google::protobuf::Metadata List::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace list
}  // namespace cpm
}  // namespace cat
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_CPMList_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
