// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaNvmCalOnTheFlyDataChannel_Channel_Output_H
#define LpsSaNvmCalOnTheFlyDataChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaNvmCalOnTheFlyDataChannel/LpsSaNvmCalOnTheFlyDataChannel.h>

DefineOutputChannel(LpsSaNvmCalOnTheFlyDataChannel.Channel.Output, LpsSaNvmCalOnTheFlyDataChannel)

#endif

