// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef DemoAppReqstChannel_Channel_Output_H
#define DemoAppReqstChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/DemoAppReqstChannel/DemoAppReqstChannel.h>

DefineOutputChannel(DemoAppReqstChannel.Channel.Output, DemoAppReqstChannel)

#endif

