// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaWeighDebugChannel_Channel_Input_H
#define LpsSaWeighDebugChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaWeighDebugChannel/LpsSaWeighDebugChannel.h>

DefineInputChannel(LpsSaWeighDebugChannel.Channel.Input, LpsSaWeighDebugChannel)

#endif

