// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'
#include "channel.h"
#include <ais/PluginProcessor/PluginDefine.h>

RegisterPlugin(LpsSaWeighTxChannel.Channel.Output, interfaces::Interface, LpsSaWeighTxChannelOutputChannel)
