// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaWeighTxChannel_Channel_Output_H
#define LpsSaWeighTxChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaWeighTxChannel/LpsSaWeighTxChannel.h>

DefineOutputChannel(LpsSaWeighTxChannel.Channel.Output, LpsSaWeighTxChannel)

#endif

