// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaNvmCalDataChannel_Channel_Input_H
#define LpsSaNvmCalDataChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaNvmCalDataChannel/LpsSaNvmCalDataChannel.h>

DefineInputChannel(LpsSaNvmCalDataChannel.Channel.Input, LpsSaNvmCalDataChannel)

#endif

