// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef Machine_Channel_Input_H
#define Machine_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/Machine/Machine.h>

DefineInputChannel(Machine.Channel.Input, Machine)

#endif

