// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef DemoAppReqstChannel_Channel_Input_H
#define DemoAppReqstChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/DemoAppReqstChannel/DemoAppReqstChannel.h>

DefineInputChannel(DemoAppReqstChannel.Channel.Input, DemoAppReqstChannel)

#endif

