// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaWeighInitDebugChannel_Channel_Input_H
#define LpsSaWeighInitDebugChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaWeighInitDebugChannel/LpsSaWeighInitDebugChannel.h>

DefineInputChannel(LpsSaWeighInitDebugChannel.Channel.Input, LpsSaWeighInitDebugChannel)

#endif

