// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaNvmCalDataChannel_Channel_Output_H
#define LpsSaNvmCalDataChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaNvmCalDataChannel/LpsSaNvmCalDataChannel.h>

DefineOutputChannel(LpsSaNvmCalDataChannel.Channel.Output, LpsSaNvmCalDataChannel)

#endif

