// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef AisJhm2TxChannel_Channel_Output_H
#define AisJhm2TxChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/AisJhm2TxChannel/AisJhm2TxChannel.h>

DefineOutputChannel(AisJhm2TxChannel.Channel.Output, AisJhm2TxChannel)

#endif

