// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'
#include "channel.h"
#include <ais/PluginProcessor/PluginDefine.h>

RegisterPlugin(AisJhm2TxChannel.Channel.Output, interfaces::Interface, AisJhm2TxChannelOutputChannel)
