// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaJobMgrDebugChannel_Channel_Input_H
#define LpsSaJobMgrDebugChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaJobMgrDebugChannel/LpsSaJobMgrDebugChannel.h>

DefineInputChannel(LpsSaJobMgrDebugChannel.Channel.Input, LpsSaJobMgrDebugChannel)

#endif

