// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaJobMgrRespChannel_Channel_Input_H
#define LpsSaJobMgrRespChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaJobMgrRespChannel/LpsSaJobMgrRespChannel.h>

DefineInputChannel(LpsSaJobMgrRespChannel.Channel.Input, LpsSaJobMgrRespChannel)

#endif

