// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef AisJhm2TxChannel_Channel_Input_H
#define AisJhm2TxChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/AisJhm2TxChannel/AisJhm2TxChannel.h>

DefineInputChannel(AisJhm2TxChannel.Channel.Input, AisJhm2TxChannel)

#endif

