// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'
#include "channel.h"
#include <ais/PluginProcessor/PluginDefine.h>

RegisterPlugin(AisJhm2TxChannel.Channel.Input, interfaces::Interface, AisJhm2TxChannelInputChannel)
