###############################################################################
## @file      SConscript
## @author    Bryan Salesky (bsalesky@rec.ri.cmu.edu)
## @date      May 16, 2008
## @brief     SConscript for the testTask application.
##
## @attention Copyright (C) 2008
## @attention National Robotics Engineering Center
## @attention Carnegie Mellon University
## @attention All rights reserved
## @attention Carnegie Mellon Proprietary
###############################################################################
Import( 'testEnv' )

testEnv.Append( LIBPATH = [ '#/apps/lib',
			 ] )

testEnv.Append( CPPPATH = [ '.', 
			    '#/apps/include',
			    '#/widgets/tire_rev_wl00/include',
			    '#/widgets/dig_timer_wl00/include',			    
			    '#prod/infrastructure/catdl',
			    '#/mach_prod_pcs-interface/include',
			    '#/mach_prod_prodcore/include'
			    ] )

sourceFiles = \
    Glob('*.cpp')+ \
    Glob('*.c')+ \
    Glob('#/widgets/tire_rev_wl00/src/*.c') + \
    Glob('#/widgets/dig_timer_wl00/src/*.c')

WidgetApp = testEnv.Program(
        target = 'WidgetApp',
        source = sourceFiles,
        LIBS = [ 'ais_task', 'ais_config', 'ais_log' ]
    )

testEnv.InstallBinary( WidgetApp )


testEnv.Alias("WidgetApp", "#bin/WidgetApp")


