// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#include <ais/serialization/TypeRestorer.h>
#include <ais/interfaces/traits/TextWritable.h>
#include <interfaces/LpsSaWeighInitDebugChannel/LpsSaWeighInitDebugChannel.h>

extern "C"  
{
    TextWritable *getTextWritable(const void *blob, const unsigned int size)
    {
        TypeRestorer rest;
        return rest.restoreAltType<LpsSaWeighInitDebugChannel, TextWritable *>(blob, size);
    }
}

