###############################################################################
## @file      SConscript
## @author    Bryan Salesky (bsalesky@rec.ri.cmu.edu)
## @date      May 16, 2008
## @brief     SConscript for the test/ directory.
##
## @attention Copyright (C) 2008
## @attention National Robotics Engineering Center
## @attention Carnegie Mellon University
## @attention All rights reserved
## @attention Carnegie Mellon Proprietary
###############################################################################
#!/usr/bin/python
Import( 'baseEnv' )
testEnv = baseEnv.Clone();
Export( 'testEnv' )

testEnv.buildit( 'sl_cal', ['suse'] )
#testEnv.buildit( 'apriltag', ['suse'] )
