// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaWeighReqstChannel_Channel_Output_H
#define LpsSaWeighReqstChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaWeighReqstChannel/LpsSaWeighReqstChannel.h>

DefineOutputChannel(LpsSaWeighReqstChannel.Channel.Output, LpsSaWeighReqstChannel)

#endif

