// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaWeighInitDebugChannel_Channel_Output_H
#define LpsSaWeighInitDebugChannel_Channel_Output_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaWeighInitDebugChannel/LpsSaWeighInitDebugChannel.h>

DefineOutputChannel(LpsSaWeighInitDebugChannel.Channel.Output, LpsSaWeighInitDebugChannel)

#endif

