// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef TipoffModelTestPoints_Channel_Input_H
#define TipoffModelTestPoints_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/TipoffModelTestPoints/TipoffModelTestPoints.h>

DefineInputChannel(TipoffModelTestPoints.Channel.Input, TipoffModelTestPoints)

#endif

