// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#ifndef LpsSaJobMgrTxChannel_Channel_Input_H
#define LpsSaJobMgrTxChannel_Channel_Input_H

#include <ais/interfaces/baseTypes/autogen_channel.h>
#include <interfaces/LpsSaJobMgrTxChannel/LpsSaJobMgrTxChannel.h>

DefineInputChannel(LpsSaJobMgrTxChannel.Channel.Input, LpsSaJobMgrTxChannel)

#endif

