// Do NOT modify -- Auto-generated by 'interfaces/autogen/generate'

#include <ais/serialization/TypeRestorer.h>
#include <ais/interfaces/traits/csvable.h>
#include <interfaces/DemoAppReqstChannel/DemoAppReqstChannel.h>

extern "C"  
{
    csvable *getCSVable(const void *blob, const unsigned int size) 
    {
        TypeRestorer rest;
        return rest.restoreAltType<DemoAppReqstChannel, csvable *>(blob, size);
    }
}

