###############################################################################
## @file      SConscript
## @author    autogen
##
## @attention Copyright (C) 2017
## @attention National Robotics Engineering Center
## @attention Carnegie Mellon University
## @attention All rights reserved
## @attention Carnegie Mellon Proprietary
###############################################################################
#!/usr/bin/python
Import( 'baseEnv' )

baseEnv.Append(CPPPATH = [ 
    		'#/lps_cal/include',
			]);

# Build Channel.Input.so
ifaceChannelInput = baseEnv.SharedLibraryWrapper(
    target='LpsSaNvmCalOnTheFlyDataChannel.Channel.Input.so',
    source='Channel/Input/channel.cpp',
    LIBS = ['ais_serialization', 'ais_channel', baseEnv['BOOST_SIGNALS'] ],
)

# Build Channel.Output.so
ifaceChannelOutput = baseEnv.SharedLibraryWrapper(
    target='LpsSaNvmCalOnTheFlyDataChannel.Channel.Output.so',
    source='Channel/Output/channel.cpp',
    LIBS = ['ais_serialization', 'ais_channel' ],
)

# Build Restorable
ifaceRestorable = baseEnv.SharedLibraryWrapper(
    target='LpsSaNvmCalOnTheFlyDataChannel.Restorable.so',
    source='Restorable/Restorable.cpp',
    LIBS = ['ais_serialization'],
)
    
# Build TypeTraits    
ifaceTypeTraits = baseEnv.SharedLibraryWrapper(
  target='LpsSaNvmCalOnTheFlyDataChannel.TypeTraits.so',
  source=[
       'TypeTraits/csvable.cpp',
        'TypeTraits/textWritable.cpp',
   ],
   LIBS = ['ais_serialization'],
)

baseEnv.InstallLibrary( ifaceChannelInput )
baseEnv.InstallLibrary( ifaceChannelOutput )
baseEnv.InstallLibrary( ifaceRestorable )
baseEnv.InstallLibrary( ifaceTypeTraits )

baseEnv.Alias("LpsSaNvmCalOnTheFlyDataChannel", "#lib/libLpsSaNvmCalOnTheFlyDataChannel.Channel.Input.so")
baseEnv.Alias("LpsSaNvmCalOnTheFlyDataChannel", "#lib/libLpsSaNvmCalOnTheFlyDataChannel.Channel.Output.so")
baseEnv.Alias("LpsSaNvmCalOnTheFlyDataChannel", "#lib/libLpsSaNvmCalOnTheFlyDataChannel.Restorable.so")
baseEnv.Alias("LpsSaNvmCalOnTheFlyDataChannel", "#lib/libLpsSaNvmCalOnTheFlyDataChannel.TypeTraits.so")
